// app/javascript/check-stamp.vue
<template lang="pug">
.stamp.stamp-approve(v-if='checkId')
  h2.stamp__content.is-title
    | 確認済
  time.stamp__content.is-created-at
    | {{ checkCreatedAt }}
  .stamp__content.is-user-name
    | {{ checkUserName }}
</template>
<script>
import 'whatwg-fetch'

export default {
  props: ['checkableId', 'checkableType'],
  computed: {
    checkId() {
      return this.$store.getters.checkId
    },
    checkCreatedAt() {
      return this.$store.getters.createdAt
    },
    checkUserName() {
      return this.$store.getters.userName
    }
  },
  mounted() {
    this.$store.dispatch('setCheckable', {
      checkableId: this.checkableId,
      checkableType: this.checkableType
    })
  }
}
</script>

// app/javascript/components/Check/CheckStamp.jsx
import React from 'react'
import { useCheck } from './useCheck'

const CheckStamp = ({ checkableId, checkableType }) => {
  const { checkId, createdAt, userName } = useCheck(checkableId, checkableType)

  return (
    <div className={checkId ? 'stamp stamp-approve' : ''}>
      {checkId && (
        <>
          <h2 className="stamp__content is-title">確認済</h2>
          <time className="stamp__content is-created-at">{createdAt}</time>
          <div className="stamp__content is-user-name">
            <div className="stamp__content-inner">{userName}</div>
          </div>
        </>
      )}
    </div>
  )
}

export default CheckStamp
