// app/javascript/admin_companies.vue
<template lang="pug">
.container.is-lg
  nav.pagination(v-if='totalPages > 1')
    pager(v-bind='pagerProps')
  .admin-table
    table.admin-table__table
      thead.admin-table__header
        tr.admin-table__labels
          th.admin-table__label
            | 名前
          th.admin-table__label
            | ロゴ
          th.admin-table__label
            | ウェブサイト
          th.admin-table__label.actions
            | アドバイザー招待
          th.admin-table__label.actions
            | 編集
      tbody.admin-table__items
        tr.admin-table__item(
          v-for='company in companies',
          :key='company.id',
          :id='`company_${company.id}`',
          v-if='companies'
        )
          td.admin-table__item-value
            | {{ company.name }}
          td.admin-table__item-value.is-text-align-center
            img.admin-table__item-logo-image(
              v-if='company.logo_url',
              :src='company.logo_url'
            )
          td.admin-table__item-value
            | {{ company.website }}
          td.admin-table__item-value.is-text-align-center
            a.a-button.is-sm.is-secondary.is-icon(
              :title='"アドバイザーサインアップURL"',
              :href='company.adviser_sign_up_url'
            )
              i.fa-solid.fa-user-plus
          td.admin-table__item-value.is-text-align-center
            ul.is-inline-buttons
              li
                a.a-button.is-sm.is-secondary.is-icon(
                  :href='`/admin/companies/${company.id}/edit`'
                )
                  i.fa-solid.fa-pen
  nav.pagination(v-if='totalPages > 1')
    pager(v-bind='pagerProps')
</template>

<script>
import Pager from 'pager'
import toast from 'toast'

export default {
  components: {
    pager: Pager
  },
  mixins: [toast],
  data() {
    return {
      companies: [],
      totalPages: 0,
      currentPage: this.getCurrentPage(),
      loaded: false
    }
  },
  computed: {
    url() {
      return `/api/admin/companies?page=${this.currentPage}`
    },
    pagerProps() {
      return {
        initialPageNumber: this.currentPage,
        pageCount: this.totalPages,
        pageRange: 5,
        clickHandle: this.paginateClickCallback
      }
    }
  },
  created() {
    window.onpopstate = () => {
      this.currentPage = this.getCurrentPage()
      this.getCompaniesPage()
    }
    this.getCompaniesPage()
  },
  methods: {
    token() {
      const meta = document.querySelector('meta[name="csrf-token"]')
      return meta ? meta.getAttribute('content') : ''
    },
    getCompaniesPage() {
      fetch(this.url, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': this.token()
        },
        credentials: 'same-origin',
        redirect: 'manual'
      })
        .then((response) => response.json())
        .then((json) => {
          this.companies = json.companies
          this.totalPages = json.total_pages
          this.loaded = true
        })
        .catch((error) => {
          console.warn(error)
        })
    },
    destroy(company) {
      if (window.confirm('本当によろしいですか？')) {
        fetch(`/api/admin/companies/${company.id}.json`, {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json; charset=utf-8',
            'X-Requested-With': 'XMLHttpRequest',
            'X-CSRF-Token': this.token()
          },
          credentials: 'same-origin',
          redirect: 'manual'
        })
          .then((response) => {
            if (response.ok) {
              // eslint-disable-next-line vue/no-mutating-props
              this.companies = this.companies.filter((v) => v.id !== company.id)
              this.toast('企業を削除しました。')
            } else {
              alert('削除に失敗しました')
            }
          })
          .catch((error) => {
            console.warn(error)
          })
      }
    },
    getCurrentPage() {
      const params = new URLSearchParams(location.search)
      const page = params.get('page')
      return parseInt(page) || 1
    },
    paginateClickCallback(pageNumber) {
      this.currentPage = pageNumber
      this.getCompaniesPage()

      const url = new URL(location.href)
      if (pageNumber === 1) {
        url.searchParams.delete('page')
      } else {
        url.searchParams.set('page', pageNumber)
      }
      history.pushState(history.state, '', url)
      window.scrollTo(0, 0)
    }
  }
}
</script>

// app/javascript/components/AdminCompanies.jsx
import React, { useState, useEffect } from 'react'
import queryString from 'query-string'
import useSWR from 'swr'
import fetcher from '../fetcher'
import Pagination from './Pagination'

export default function AdminCompanies() {
  const per = 20
  const neighbours = 4
  const defaultPage = parseInt(queryString.parse(location.search).page) || 1
  const [page, setPage] = useState(defaultPage)

  useEffect(() => {
    setPage(page)
  }, [page])

  const { data, error } = useSWR(
    `/api/admin/companies.json?page=${page}&per=${per}`,
    fetcher
  )
  if (error) return <>An error has occurred.</>
  if (!data) return <>Loading...</>

  const handlePaginate = (p) => {
    setPage(p)
    window.history.pushState(null, null, `/admin/companies?page=${p}`)
  }

  return (
    <>
      <Pagination
        sum={data.total_pages * per}
        per={per}
        neighbours={neighbours}
        page={page}
        onChange={(e) => handlePaginate(e.page)}
      />
      <div className="admin-table">
        <table className="admin-table__table">
          <thead className="admin-table__header">
            <tr className="admin-table__labels">
              <th className="admin-table__label">名前</th>
              <th className="admin-table__label">ロゴ</th>
              <th className="admin-table__label">ウェブサイト</th>
              <th className="admin-table__label">アドバイザー招待リンク</th>
              <th className="admin-table__label">研修生招待リンク</th>
              <th className="admin-table__label actions">編集</th>
            </tr>
          </thead>
          <tbody className="admin-table__items">
            {data.companies.map((company) => {
              return <AdminCompany key={company.id} company={company} />
            })}
          </tbody>
        </table>
      </div>
      <Pagination
        sum={data.total_pages * per}
        per={per}
        neighbours={neighbours}
        page={page}
        onChange={(e) => handlePaginate(e.page)}
      />
    </>
  )
}

const AdminCompany = ({ company }) => {
  const url = `/companies/${company.id}`
  const editUrl = `/admin/companies/${company.id}/edit`

  return (
    <tr className="admin-table__item">
      <td className="admin-table__item-value">
        <a href={url}>{company.name}</a>
      </td>
      <td className="admin-table__item-value">
        <img className="admin-table__item-logo-image" src={company.logo_url} />
      </td>
      <td className="admin-table__item-value">{company.website}</td>
      <td className="admin-table__item-value is-text-align-center">
        <a
          title="アドバイザーサインアップURL"
          href={company.adviser_sign_up_url}
          className="a-button is-sm is-secondary is-icon">
          <i className="fa-solid fa-user-plus"></i>
        </a>
      </td>
      <td className="admin-table__item-value is-text-align-center">
        <a
          title="アドバイザーサインアップURL"
          href={company.trainee_sign_up_url}
          className="a-button is-sm is-secondary is-icon">
          <i className="fa-solid fa-user-plus"></i>
        </a>
      </td>
      <td className="admin-table__item-value is-text-align-center">
        <a
          title="アドバイザーサインアップURL"
          href={editUrl}
          className="a-button is-sm is-secondary is-icon">
          <i className="fa-solid fa-pen"></i>
        </a>
      </td>
    </tr>
  )
}
