// app/javascript/admin_courses.vue
<template lang="pug">
  .container.is-lg
    .admin-table
      table.admin-table__table
        thead.admin-table__header
          tr.admin-table__labels
            th.admin-table__label
              | コース名
            th.admin-table__label
              | 説明文
            th.admin-table__label
              | 操作
        tbody.admin-table__items
          tr.admin-table__item(
            v-for='edge in courses.edges',
            :key='edge.node.id',
            :id='`course_${edge.node.id}`',
            v-if='courses.edges'
          )
            td.admin-table__item-value
              | {{ edge.node  }}
            td.admin-table__item-value
            td.admin-table__item-value.is-text-align-center
              ul.is-inline-buttons
                li
                  i.fa-solid.fa-pen
</template>
<script>
import gql from 'graphql-tag'

const query = gql`
query {
  courses {
    edges {
      node {
        id
        title
        description
        published
        createdAt
        updatedAt
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      startCursor
      hasPreviousPage
    }
  }
}
`

export default {
  data () {
    return {
      courses: [],
      loading: null
    }
  },
  apollo: {
    courses: query,
  },
}
</script>

// app/javascript/components/AdminCourses.jsx
import React from 'react'
import useSWR from 'swr'
import fetcher from '../fetcher'

const Header = () => {
  return (
    <thead className="admin-table__header">
      <tr className="admin-table__labels">
        <td className="admin-table__label">コース名</td>
        <td className="admin-table__label">説明文</td>
        <td className="admin-table__label actions">操作</td>
      </tr>
    </thead>
  )
}

export default function AdminCourses() {
  const { data, error } = useSWR('/api/courses.json', fetcher)
  if (error) return <>An error has occurred.</>
  if (!data) return <>Loading...</>
  const courses = data.courses

  return (
    <div className="admin-table">
      <table className="admin-table__table">
        <Header />
        <tbody className="admin-table__items">
          {courses.map((course) => {
            return <AdminCourse key={course.id} course={course} />
          })}
        </tbody>
      </table>
    </div>
  )
}

function AdminCourse(props) {
  const course = props.course
  const url = `/courses/${course.id}/practices`
  const editUrl = `/admin/courses/${course.id}/edit`
  const sortUrl = `/courses/${course.id}/categories`

  return (
    <tr className="admin-table__item">
      <td className="admin-table__item-value">
        <a href={url}>{course.title}</a>
      </td>
      <td className="admin-table__item-value">{course.description}</td>
      <td className="admin-table__item-value admin-table__item-value is-text-align-center">
        <ul className="is-inline-buttons">
          <li>
            <a
              href={editUrl}
              className="a-button is-sm is-secondary is-icon is-block"
            >
              <i className="fa fa-solid fa-pen" />
            </a>
          </li>
          <li>
            <a
              href={sortUrl}
              className="a-button is-sm is-secondary is-icon is-block"
            >
              <i className="fa-solid fa-align-justify" />
            </a>
          </li>
        </ul>
      </td>
    </tr>
  )
}
