// app/javascript/components/GenerationUsers.jsx
import React, { useState, useEffect, useMemo } from 'react'
import User from './User.jsx'
import Pager from './Pager.jsx'
import CSRF from 'csrf'

const getParams = () => {
  const params = new URLSearchParams(location.search)
  const result = {}
  for (const [key, value] of params) {
    result[key] = value
  }
  if (location.pathname.match(/tags/)) {
    const tag = location.pathname.split('/').pop()
    result.tag = tag
  }
  return result
}

export default function GenerationUsers({ generationID }) {
  const [users, setUsers] = useState(null)
  const [currentUser, setCurrentUser] = useState(null)
  const [currentTarget, setCurrentTarget] = useState(null)
  const [currentTag, setCurrentTag] = useState(null)
  const [currentPage, setCurrentPage] = useState(Number(getParams().page) || 1)
  const [totalPages, setTotalPages] = useState(0)
  const [params] = useState(getParams())

  const targetName = useMemo(
    () => currentTag || currentTarget,
    [currentTag, currentTarget]
  )

  useEffect(() => {
    window.onpopstate = () => {
      location.replace(location.href)
    }
    getUsers()
  }, [])

  useEffect(() => {
    getUsers()
  }, [currentPage, params])

  const getUsers = () => {
    const url =
      `/api/generations/${generationID}.json` +
      (params.tag ? `tags/${params.tag}` : '') +
      `?page=${currentPage}` +
      (params.target ? `&target=${params.target}` : '') +
      (params.watch ? `&watch=${params.watch}` : '')
    fetch(url, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
        'X-Requested-With': 'XMLHttpRequest',
        'X-CSRF-Token': CSRF.getToken()
      },
      credentials: 'same-origin',
      redirect: 'manual'
    })
      .then((response) => response.json())
      .then((json) => {
        setUsers(json.users)
        setCurrentUser(json.currentUser)
        setCurrentTarget(json.target)
        setCurrentTag(json.tag)
        setTotalPages(json.totalPages)
      })
      .catch((error) => {
        console.warn(error)
      })
  }

  const paginateClickCallback = (pageNumber) => {
    setCurrentPage(pageNumber)
    history.pushState(null, null, newUrl(pageNumber))
    window.scrollTo(0, 0)
  }

  const newUrl = (pageNumber) => {
    let url = location.pathname
    url += params.target ? `?target=${params.target}` : ''
    url += pageNumber === 1 ? '' : `&page=${pageNumber}`
    return url
  }

  const pagerProps = {
    initialPageNumber: currentPage,
    pageCount: totalPages,
    pageRange: 5,
    clickHandle: paginateClickCallback
  }

  return (
    <div className="page-body">
      {totalPages > 1 && (
        <nav className="pagination">
          <div className="container">
            <Pager {...pagerProps} />
          </div>
        </nav>
      )}
      <div className="container">
        <div className="users">
          {users === null ? (
            <div className="row">
              <div className="empty">
                <i className="fa-solid fa-spinner fa-pulse" />
                ロード中
              </div>
            </div>
          ) : users.length !== 0 ? (
            users.map((user) => (
              <User key={user.id} user={user} currentUser={currentUser} />
            ))
          ) : (
            <div className="row">
              <div className="o-empty-message">
                <div className="o-empty-message__icon">
                  <i className="fa-regular fa-smile"></i>
                </div>
                <p className="o-empty-message_text">
                  {generationID}期のユーザー一覧はありません
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
      {totalPages > 1 && (
        <nav className="pagination">
          <div className="container">
            <Pager {...pagerProps} />
          </div>
        </nav>
      )}
    </div>
  )
}

// app/javascript/components/generation-users.vue
<template lang="pug">
.page-body
  nav.pagination(v-if='totalPages > 1')
    pager(v-bind='pagerProps')
  .container
    .users
      .row(v-if='users === null')
        .empty
          .fa-solid.fa-spinner.fa-pulse
          |
          | ロード中
      .row(v-else-if='users.length !== 0')
        user(
          v-for='user in users',
          :key='user.id',
          :user='user',
          :currentUser='currentUser')
      .row(v-else)
        .o-empty-message
          .o-empty-message__icon
            i.fa-regular.fa-smile
          p.o-empty-message__text
            | {{ generationID }}期のユーザー一覧はありません
  nav.pagination(v-if='totalPages > 1')
    pager(v-bind='pagerProps')
</template>
<script>
import User from './user.vue'
import Pager from '../pager.vue'

export default {
  name: 'GenerationUsers',
  components: {
    user: User,
    pager: Pager
  },
  props: {
    generationID: { type: Number, required: true }
  },
  data() {
    return {
      users: null,
      currentUser: null,
      currentTarget: null,
      currentTag: null,
      currentPage: Number(this.getParams().page) || 1,
      totalPages: 0,
      params: this.getParams()
    }
  },
  computed: {
    targetName() {
      return this.currentTag || this.currentTarget
    },
    url() {
      return (
        `/api/generations/${this.generationID}.json` +
        (this.params.tag ? `tags/${this.params.tag}` : '') +
        `?page=${this.currentPage}` +
        (this.params.target ? `&target=${this.params.target}` : '') +
        (this.params.watch ? `&watch=${this.params.watch}` : '')
      )
    },
    pagerProps() {
      return {
        initialPageNumber: this.currentPage,
        pageCount: this.totalPages,
        pageRange: 5,
        clickHandle: this.paginateClickCallback
      }
    }
  },
  created() {
    window.onpopstate = () => {
      location.replace(location.href)
    }
    this.getUsers()
  },
  methods: {
    token() {
      const meta = document.querySelector('meta[name="csrf-token"]')
      return meta ? meta.getAttribute('content') : ''
    },
    getUsers() {
      fetch(this.url, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': this.token()
        },
        credentials: 'same-origin',
        redirect: 'manual'
      })
        .then((response) => {
          return response.json()
        })
        .then((json) => {
          this.users = []
          json.users.forEach((user) => {
            this.users.push(user)
          })
          this.currentUser = json.currentUser
          this.currentTarget = json.target
          this.currentTag = json.tag
          this.totalPages = json.totalPages
        })
        .catch((error) => {
          console.warn(error)
        })
    },
    getParams() {
      const params = {}
      location.search
        .slice(1)
        .split('&')
        .forEach((query) => {
          const queryArr = query.split('=')
          params[queryArr[0]] = queryArr[1]
        })
      if (location.pathname.match(/tags/)) {
        const tag = location.pathname.split('/').pop()
        params.tag = tag
      }
      return params
    },
    paginateClickCallback(pageNumber) {
      this.currentPage = pageNumber
      this.getUsers()
      history.pushState(null, null, this.newUrl(pageNumber))
      window.scrollTo(0, 0)
    },
    newUrl(pageNumber) {
      if (this.params.target) {
        return (
          location.pathname +
          `?target=${this.params.target}` +
          (pageNumber === 1 ? '' : `&page=${pageNumber}`)
        )
      } else {
        return (
          location.pathname + (pageNumber === 1 ? '' : `?page=${pageNumber}`)
        )
      }
    }
  }
}
</script>
