// app/javascript/pager.vue
<template>
  <div>
    <pager
      :value='initialPageNumber'
      :page-count='pageCount'
      :page-range='pageRange'
      :prev-text='makeITag("left")'
      :next-text='makeITag("right")'
      :click-handler='clickHandle'
      :first-button-text='makeITag("double-left")'
      :last-button-text='makeITag("double-right")'
      :margin-pages='0'
      first-last-button
      hide-prev-next
      container-class='pagination__items'
      page-class='pagination__item'
      page-link-class='pagination__item-link'
      prev-class='pagination__item is-prev'
      prev-link-class='pagination__item-link is-prev'
      next-class='pagination__item is-next'
      next-link-class='pagination__item-link is-next'
      active-class='is-active'
      disabled-class='is-disabled'></pager>
  </div>
</template>

<script>
import VuejsPaginate from 'vuejs-paginate'

export default {
  components: {
    pager: VuejsPaginate
  },
  props: {
    initialPageNumber: { type: Number, required: true },
    pageCount: { type: Number, required: true },
    pageRange: { type: Number, required: true },
    clickHandle: { type: Function, required: true }
  },
  methods: {
    makeITag(iconName) {
      return `<i class='fas fa-angle-${iconName}'></i>`
    }
  }
}
</script>

// app/javascript/components/Pager.jsx
import React from 'react'
import ReactPaginate from 'react-paginate'

export default function Pager({
  initialPageNumber,
  pageCount,
  pageRange,
  clickHandle
}) {
  const makeITag = (iconName) => <i className={`fas fa-angle-${iconName}`}></i>

  return (
    <div className="pagination-container">
      <button onClick={() => clickHandle(1)} className="pagination__item-link">
        {makeITag('double-left')}
      </button>

      <ReactPaginate
        forcePage={initialPageNumber - 1}
        pageCount={pageCount}
        pageRangeDisplayed={pageRange}
        marginPagesDisplayed={0}
        previousLabel={makeITag('left')}
        nextLabel={makeITag('right')}
        onPageChange={(e) => clickHandle(e.selected + 1)}
        containerClassName="pagination__items"
        pageClassName="pagination__item"
        pageLinkClassName="pagination__item-link"
        previousClassName="pagination__item is-prev"
        previousLinkClassName="pagination__item-link is-prev"
        nextClassName="pagination__item is-next"
        nextLinkClassName="pagination__item-link is-next"
        activeClassName="is-active"
        disabledClassName="is-disabled"
      />

      <button
        onClick={() => clickHandle(pageCount)}
        className="pagination__item-link">
        {makeITag('double-right')}
      </button>
    </div>
  )
}
