// app/javascript/regular-events.vue
<template lang="pug">
.page-content.loaing(v-if='!loaded')
  | ロード中
.page-content.loaded(v-else)
  nav.pagination(v-if='totalPages > 1')
    pager(v-bind='pagerProps')
  .card-list.a-card
    regularEvent(
      v-for='regularEvent in regularEvents',
      :key='regularEvent.id',
      :regularEvent='regularEvent'
    )
  nav.pagination(v-if='totalPages > 1')
    pager(v-bind='pagerProps')
</template>

<script>
import RegularEvent from 'regular-event'
import Pager from 'pager'

export default {
  components: {
    regularEvent: RegularEvent,
    pager: Pager
  },
  data() {
    return {
      regularEvents: [],
      totalPages: 0,
      currentPage: this.getCurrentPage(),
      loaded: false
    }
  },
  computed: {
    url() {
      const params = new URL(location.href).searchParams
      params.set('page', this.currentPage)
      return `/api/regular_events?${params}`
    },
    pagerProps() {
      return {
        initialPageNumber: this.currentPage,
        pageCount: this.totalPages,
        pageRange: 5,
        clickHandle: this.paginateClickCallback
      }
    }
  },
  created() {
    window.onpopstate = () => {
      this.currentPage = this.getCurrentPage()
      this.getEventsPerPage()
    }
    this.getEventsPerPage()
  },
  methods: {
    token() {
      const meta = document.querySelector('meta[name="csrf-token"]')
      return meta ? meta.getAttribute('content') : ''
    },
    getEventsPerPage() {
      fetch(this.url, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': this.token()
        },
        credentials: 'same-origin',
        redirect: 'manual'
      })
        .then((response) => response.json())
        .then((json) => {
          this.regularEvents = json.regular_events
          this.totalPages = json.total_pages
          this.loaded = true
        })
        .catch((error) => {
          console.warn(error)
        })
    },
    getCurrentPage() {
      const params = new URLSearchParams(location.search)
      const page = params.get('page')
      return parseInt(page) || 1
    },
    paginateClickCallback(pageNumber) {
      this.currentPage = pageNumber
      this.getEventsPerPage()

      const url = new URL(location.href)
      if (pageNumber === 1) {
        url.searchParams.delete('page')
      } else {
        url.searchParams.set('page', pageNumber)
      }
      history.pushState(history.state, '', url)
      window.scrollTo(0, 0)
    }
  }
}
</script>

// app/javascript/components/RegularEvents.jsx
import React, { useState, useEffect } from 'react'
import useSWR from 'swr'
import fetcher from '../fetcher'
import queryString from 'query-string'
import Pagination from './Pagination'
import RegularEvent from './RegularEvent'

const RegularEvents = () => {
  const per = 20
  const neighbours = 4
  const defaultPage = parseInt(queryString.parse(location.search).page) || 1
  const [page, setPage] = useState(defaultPage)

  useEffect(() => {
    setPage(page)
  }, [page])

  const params = new URL(location.href).searchParams
  params.set('page', page)
  const { data, error } = useSWR(`/api/regular_events?${params}`, fetcher)

  const handlePaginate = (p) => {
    setPage(p)
    window.history.pushState(null, null, `/regular_events?${params}`)
  }

  if (error) console.warn(error)
  if (!data) return <div className="page-content loaing">ロード中…</div>

  return (
    <div className="page-content loaded">
      {data.total_pages > 1 && (
        <Pagination
          sum={data.total_pages * per}
          per={per}
          neighbours={neighbours}
          page={page}
          onChange={(e) => handlePaginate(e.page)}
        />
      )}
      <div className="card-list a-card">
        {data.regular_events.map(regularEvent =>
          <RegularEvent
            key={regularEvent.id}
            regularEvent={regularEvent}
          />
        )}
      </div>
      {data.total_pages > 1 && (
        <Pagination
          sum={data.total_pages * per}
          per={per}
          neighbours={neighbours}
          page={page}
          onChange={(e) => handlePaginate(e.page)}
        />
      )}
    </div>
  )
}

export default RegularEvents
