// app/javascript/components/Reports.jsx
import React, { useState, useEffect } from 'react'
import useSWR from 'swr'
import fetcher from '../fetcher'
import LoadingListPlaceholder from './LoadingListPlaceholder'
import Report from './Report'
import Pagination from './Pagination'
import PracticeFilterDropdown from './PracticeFilterDropdown'
import UnconfirmedLink from './UnconfirmedLink'
import usePage from './hooks/usePage'

export default function Reports({
  all = false,
  userId = '',
  practices = false,
  unchecked = false,
  displayUserIcon = true,
  companyId = '',
  practiceId = '',
  displayPagination = true
}) {
  const per = 20
  const { page, setPage } = usePage()
  const [userPracticeId, setUserPracticeId] = useState('')

  useEffect(() => {
    setUserPracticeId(userPracticeId)
  }, [userPracticeId])

  const { data, error } = useSWR(
    practices
      ? `/api/reports.json?user_id=${userId}&page=${page}&practice_id=${userPracticeId}`
      : unchecked
      ? `/api/reports/unchecked.json?page=${page}&user_id=${userId}`
      : userId !== ''
      ? `/api/reports.json?page=${page}&user_id=${userId}`
      : practiceId !== ''
      ? `/api/reports.json?page=${page}&practice_id=${practiceId}`
      : companyId !== ''
      ? `/api/reports.json?page=${page}&company_id=${companyId}`
      : all === true
      ? `/api/reports.json?page=${page}&practice_id=${userPracticeId}`
      : console.log('data_fetched!'),
    fetcher
  )

  if (error) return <>エラーが発生しました。</>
  if (!data) {
    return (
      <div className="page-main">
        <div className="page-body">
          <div className="container is-md">
            <LoadingListPlaceholder />
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="page-main">
      {data.totalPages === 0 && (
        <div>
          {practices && (
            <PracticeFilterDropdown
              practices={practices}
              setPracticeId={setUserPracticeId}
              practiceId={userPracticeId}
            />
          )}
          <NoReports unchecked={unchecked} />
        </div>
      )}
      {data.totalPages > 0 && (
        <div>
          {practices && (
            <PracticeFilterDropdown
              practices={practices}
              setPracticeId={setUserPracticeId}
              practiceId={userPracticeId}
            />
          )}
          <div className="page-body">
            <div className="container is-md">
              <div className="page-content reports">
                {data.totalPages > 1 && displayPagination && (
                  <Pagination
                    sum={data.totalPages * per}
                    per={per}
                    page={page}
                    setPage={setPage}
                  />
                )}
                <div className="card-list a-card">
                  <div className="card-list__items">
                    {data.reports.map((report) => {
                      return (
                        <Report
                          key={report.id}
                          report={report}
                          currentUserId={report.currentUserId}
                          displayUserIcon={displayUserIcon}
                        />
                      )
                    })}
                  </div>
                  {unchecked && (
                    <UnconfirmedLink label={'未チェックの日報を一括で開く'} />
                  )}
                </div>
                {data.totalPages > 1 && displayPagination && (
                  <Pagination
                    sum={data.totalPages * per}
                    per={per}
                    page={page}
                    setPage={setPage}
                  />
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

const NoReports = ({ unchecked }) => {
  return (
    <div className="page-main">
      <div className="page-body">
        <div className="container is-md">
          <div className="o-empty-message">
            <div className="o-empty-message__icon">
              {unchecked ? (
                <>
                  <i className="fa-regular fa-smile" />
                  <p className="o-empty-message__text">
                    未チェックの日報はありません
                  </p>
                </>
              ) : (
                <div className="card-list a-card">
            <div className="card-list__items">
                    <i className="fa-regular fa-sad-tear" />
                    <p className="o-empty-message__text">
                    日報はまだありません。
                  </p>
            </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// app/javascript/components/reports.vue
<template lang="pug">
.card-list.a-card(v-if='limit')
  .card-header.is-sm
    h2.card-header__title
      | 直近の日報
  .card-list__items(v-if='reports && reports.length > 0')
    report(
      v-for='report in reports',
      :key='report.id',
      :report='report',
      :current-user-id='currentUserId',
      :display-user-icon='displayUserIcon')
  .card-body(v-else)
    .card__description
      .o-empty-message
        .o-empty-message__icon
          i.fa-regular.fa-sad-tear
        .o-empty-message__text
          | 日報はまだありません。
.l-main-column(v-else)
  .page-content.reports
    nav.pagination(v-if='totalPages > 1')
      pager(v-bind='pagerProps')
    .reports.is-md(v-if='reports === null')
      loadingListPlaceholder
    .card-list.a-card(v-else-if='reports.length > 0')
      .card-list__items
        report(
          v-for='report in reports',
          :key='report.id',
          :report='report',
          :current-user-id='currentUserId',
          :display-user-icon='displayUserIcon')
      unconfirmed-link(v-if='isUncheckedReportsPage', label='未チェックの日報を一括で開く')
    .o-empty-message(v-else-if='reports.length === 0 && isUncheckedReportsPage')
      .o-empty-message__icon
        i.fa-regular.fa-smile
      p.o-empty-message__text
        | 未チェックの日報はありません
    .o-empty-message(v-else)
      .o-empty-message__icon
        i.fa-regular.fa-sad-tear
      .o-empty-message__text
        | 日報はまだありません。
    nav.pagination(v-if='totalPages > 1')
      pager(v-bind='pagerProps')
</template>
<script>
import Report from 'components/report.vue'
import UnconfirmedLink from 'unconfirmed_link.vue'
import LoadingListPlaceholder from 'loading-list-placeholder.vue'
import Pager from 'pager.vue'

export default {
  name: 'Reports',
  components: {
    report: Report,
    'unconfirmed-link': UnconfirmedLink,
    loadingListPlaceholder: LoadingListPlaceholder,
    pager: Pager
  },
  props: {
    userId: {
      type: Number,
      default: null
    },
    companyId: {
      type: Number,
      default: null
    },
    practiceId: {
      type: Number,
      default: null
    },
    limit: {
      type: String,
      default: null
    },
    displayUserIcon: {
      type: Boolean,
      default: true
    }
  },
  data() {
    return {
      reports: null,
      currentPage: this.pageParam(),
      totalPages: null,
      currentUserId: null
    }
  },
  computed: {
    isUncheckedReportsPage() {
      return location.pathname.includes('unchecked')
    },
    newParams() {
      const params = new URL(location.href).searchParams
      params.set('page', this.currentPage)
      if (this.userId) {
        params.set('user_id', this.userId)
      }
      if (this.companyId) {
        params.set('company_id', this.companyId)
      }
      if (this.practiceId) {
        params.set('practice_id', this.practiceId)
      }
      if (this.limit) {
        params.set('limit', this.limit)
      }
      return params
    },
    newURL() {
      return `${location.pathname}?${this.newParams}`
    },
    reportsAPI() {
      const params = this.newParams
      if (this.isUncheckedReportsPage) {
        return `/api/reports/unchecked.json?${params}`
      } else {
        return `/api/reports.json?${params}`
      }
    },
    pagerProps() {
      return {
        initialPageNumber: this.currentPage,
        pageCount: this.totalPages,
        pageRange: 9,
        clickHandle: this.clickCallback
      }
    }
  },
  created() {
    window.onpopstate = () => {
      this.currentPage = this.pageParam()
      this.getReports()
    }
    this.getReports()
  },
  methods: {
    pageParam() {
      const url = new URL(location.href)
      const page = url.searchParams.get('page')
      return parseInt(page || 1)
    },
    clickCallback(pageNum) {
      this.currentPage = pageNum
      history.pushState(null, null, this.newURL)
      this.getReports()
      window.scrollTo(0, 0)
    },
    async getReports() {
      const response = await fetch(this.reportsAPI, {
        method: 'GET',
        headers: { 'X-Requested-With': 'XMLHttpRequest' },
        credentials: 'same-origin',
        redirect: 'manual'
      }).catch((error) => console.warn(error))
      const json = await response.json().catch((error) => console.warn(error))
      this.reports = json.reports
      this.currentUserId = json.currentUserId
      this.totalPages = parseInt(json.totalPages)
    }
  }
}
</script>
