// app/javascript/report_template.vue
<template lang="pug">
.form-item-actions
  ul.form-item-actions__items
    li.form-item-actions__item(v-if='registeredTemplate !== ""')
      a.form-item-actions__text-link.is-danger(@click.prevent='replaceReport')
        | テンプレートを反映する
    li.form-item-actions__item(v-if='registeredTemplate !== ""')
      button.a-button.is-sm.is-secondary.is-block(@click.prevent='openModal') テンプレート変更
    li.form-item-actions__item(v-else)
      button.a-button.is-sm.is-secondary.is-block(@click.prevent='openModal') テンプレート登録
    modal(
      v-on:closeModal='closeModal',
      v-on:registerTemplate='registerTemplate',
      v-if='showModal',
      :editingTemplateProp='editingTemplate',
      :isTemplateRegisteredProp='isTemplateRegistered',
      :templateIdProp='templateIdProp')
</template>
<script>
import Modal from 'report_template_modal.vue'
import toast from 'toast'
import TextareaInitializer from 'textarea-initializer'

export default {
  components: {
    modal: Modal
  },
  mixins: [toast],
  props: {
    registeredTemplateProp: { type: String, required: false, default: '' },
    templateIdProp: { type: String, required: false, default: undefined }
  },
  data() {
    return {
      registeredTemplate: '',
      editingTemplate: '',
      showModal: false,
      isTemplateRegistered: false
    }
  },
  mounted() {
    const report = document.querySelector('#report_description')
    if (report.value === '') {
      report.value = this.registeredTemplateProp
      TextareaInitializer.initialize('.js-report-content')
    }
    this.registeredTemplate = this.registeredTemplateProp
    this.editingTemplate = this.registeredTemplateProp
    if (this.registeredTemplate !== '') this.isTemplateRegistered = true
  },
  methods: {
    openModal() {
      this.showModal = true
    },
    closeModal(editingTemplate) {
      this.editingTemplate = editingTemplate
      this.showModal = false
    },
    replaceReport() {
      const report = document.querySelector('#report_description')
      if (
        report.value === '' ||
        confirm('日報が上書きされますが、よろしいですか？')
      ) {
        report.value = this.registeredTemplate
        TextareaInitializer.uninitialize('.js-report-content')
        TextareaInitializer.initialize('.js-report-content')
      }
    },
    registerTemplate(template) {
      this.registeredTemplate = template
      this.toast('テンプレートを登録しました！')
    }
  }
}
</script>

// app/javascript/components/ReportTemplate.jsx
import React, { useState, useEffect } from 'react'
import ReportTemplateModal from './ReportTemplateModal'
import TextareaInitializer from '../textarea-initializer'

export default function ReportTemplate({ templateDescription, templateId }) {
  const [registeredTemplate, setRegisteredTemplate] = useState(
    templateDescription !== null ? templateDescription : ''
  )
  const [isTemplateRegistered, setIsTemplateRegistered] = useState(
    templateDescription !== null
  )
  const [editingTemplate, setEditingTemplate] = useState(registeredTemplate)
  const [showModal, setShowModal] = useState(false)

  useEffect(() => {
    const report = document.querySelector('#report_description')
    if (report.value === '') {
      report.value = registeredTemplate
      TextareaInitializer.initialize('.js-report-content')
    }
  }, [])

  const replaceReport = (e) => {
    e.preventDefault()
    const report = document.querySelector('#report_description')
    if (
      report.value === '' ||
      confirm('日報が上書きされますが、よろしいですか？')
    ) {
      report.value = registeredTemplate
      TextareaInitializer.uninitialize('.js-report-content')
      TextareaInitializer.initialize('.js-report-content')
    }
  }

  const openModal = (e) => {
    e.preventDefault()
    setShowModal(true)
  }

  const closeModal = () => {
    setShowModal(false)
  }

  return (
    <div className="form-item-actions">
      <ul className="form-item-actions__items">
        {isTemplateRegistered && (
          <li className="form-item-actions__item">
            <a
              className="form-item-actions__text-link is-danger"
              onClick={replaceReport}>
              テンプレートを反映する
            </a>
          </li>
        )}
        {isTemplateRegistered ? (
          <li className="form-item-actions__item">
            <button
              className="a-button is-sm is-secondary is-block"
              onClick={openModal}>
              テンプレート変更
            </button>
          </li>
        ) : (
          <li>
            <button
              className="a-button is-sm is-secondary is-block"
              onClick={openModal}>
              テンプレート登録
            </button>
          </li>
        )}
      </ul>
      {showModal && (
        <ReportTemplateModal
          templateId={templateId}
          setRegisteredTemplate={setRegisteredTemplate}
          isTemplateRegistered={isTemplateRegistered}
          setIsTemplateRegistered={setIsTemplateRegistered}
          editingTemplate={editingTemplate}
          setEditingTemplate={setEditingTemplate}
          closeModal={closeModal}
        />
      )}
    </div>
  )
}
