// app/javascript/components/user-practice-progress.vue
<template lang="pug">
.completed-practices-progress
  .completed-practices-progress__bar-container
    .completed-practices-progress__bar
    .completed-practices-progress__percentage-bar(
      aria-valuemax='100',
      aria-valuemin='0',
      :aria-valuenow='ariaValuenow()',
      role='progressbar',
      :style='`width: ${roundedPercentage}`')
  .completed-practices-progress__counts
    input.a-toggle-checkbox(type='checkbox', :id='`userid_${this.user.id}`')
    label.completed-practices-progress__counts-inner(
      :for='`userid_${this.user.id}`')
      .completed-practices-progress__percentage
        | {{ roundedPercentage }}
      .completed-practices-progress__number
        | {{ completedPracticesProgressNumber() }}
</template>
<script>
export default {
  props: {
    user: { type: Object, required: true }
  },
  data() {
    return {
      percentage: this.user.cached_completed_percentage,
      fraction: this.user.completed_fraction
    }
  },
  computed: {
    roundedPercentage() {
      return this.user.graduated_on ? '100%' : Math.round(this.percentage) + '%'
    }
  },
  methods: {
    ariaValuenow() {
      return this.user.graduated_on ? 100 : this.percentage
    },
    completedPracticesProgressNumber() {
      return this.user.graduated_on ? '卒業' : this.fraction
    }
  }
}
</script>

// app/javascript/components/UserPracticeProgress.jsx
import React from 'react'

export default function UserPracticeProgress({ user }) {
  const percentage = user.cached_completed_percentage
  const fraction = user.completed_fraction

  const roundedPercentage = user.graduated_on
    ? '100%'
    : Math.round(percentage) + '%'

  const ariaValuenow = user.graduated_on ? 100 : percentage

  const completedPracticesProgressNumber = user.graduated_on ? '卒業' : fraction

  return (
    <div className="completed-practices-progress">
      <div className="completed-practices-progress__bar-container">
        <div className="completed-practices-progress__bar"></div>
        <div
          className="completed-practices-progress__percentage-bar"
          aria-valuemax="100"
          aria-valuemin="0"
          aria-valuenow={ariaValuenow}
          role="progressbar"
          style={{ width: roundedPercentage }}></div>
      </div>
      <div className='completed-practices-progress__counts'>
        <input className="a-toggle-checkbox" type="checkbox" id={`userid_${user.id}`} />
        <label className="completed-practices-progress__counts-inner" htmlFor={`userid_${user.id}`}>
          <div className="completed-practices-progress__percentage">
            {roundedPercentage}
          </div>
          <div className="completed-practices-progress__number">
            {completedPracticesProgressNumber}
          </div>
        </label>
      </div>
    </div>
  )
}
