// app/javascript/components/BookmarkButton.jsx
import React, { useState, useEffect } from 'react'
import useSWR from 'swr'
import fetcher from '../fetcher'
import Bootcamp from '../bootcamp'
import toast from '../toast'

export default function BookmarkButton({ bookmarkableId, bookmarkableType }) {
  const [isBookmark, setIsBookmark] = useState('')
  let bookmarkId = null
  const bookmarkUrl = `/api/bookmarks.json?bookmarkable_type=${bookmarkableType}&bookmarkable_id=${bookmarkableId}`

  const { data, error, isLoading } = useSWR(bookmarkUrl, fetcher)
  if (error) console.log('error')
  if (isLoading) {
    return (
      <div
        id="bookmark-button"
        className="a-bookmark-button a-button is-sm is-block is-inactive is-muted">
        Bookmark
      </div>
    )
  }
  useEffect(() => {
    if (data) {
      setIsBookmark(data.bookmarks.length > 0)
      if (data.bookmarks.length > 0) {
        setIsBookmark(true)
      }
    }
  }, [data])

  if (data) {
    if (data.bookmarks.length > 0) {
      bookmarkId = data.bookmarks[0].id
    }
  }

  const bookmarkLabel = isBookmark ? 'Bookmark中' : 'Bookmark'
  const push = () => {
    if (isBookmark) {
      unbookmark()
    } else {
      bookmark()
    }
  }

  const bookmark = () => {
    Bootcamp.post(bookmarkUrl)
      .then(() => {
        setIsBookmark(true)
        toast.methods.toast('Bookmarkしました！')
      })
      .catch((error) => {
        console.warn(error)
      })
  }
  const unbookmark = () => {
    Bootcamp.delete(`/api/bookmarks/${bookmarkId}`)
      .then(() => {
        setIsBookmark(false)
        toast.methods.toast('Bookmarkを削除しました')
      })
      .catch((error) => {
        console.warn(error)
      })
  }
  return (
    <div
      id="bookmark-button"
      className={`a-bookmark-button a-button is-sm is-block ${
        isBookmark ? 'is-active is-main' : 'is-inactive is-muted'
      }`}
      onClick={() => push()}>
      {bookmarkLabel}
    </div>
  )
}

// app/javascript/bookmark-button.vue
<template lang="pug">
#bookmark-button.a-bookmark-button.a-button.is-sm.is-block(
  :class='bookmarkId ? "is-active is-main" : "is-inactive is-muted"',
  @click='push')
  | {{ bookmarkLabel }}
</template>

<script>
import CSRF from 'csrf'
import toast from 'toast'

export default {
  mixins: [toast],
  props: {
    bookmarkableId: { type: Number, required: true },
    bookmarkableType: { type: String, required: true },
    checked: { type: Boolean, required: false, default: false },
    bookmarkIndexId: { type: Number, required: false, default: 0 }
  },
  data() {
    return {
      bookmarkId: null,
      bookmarkLabel: 'Bookmark',
      totalPages: 0,
      bookmarkValue: null
    }
  },
  created() {
    this.getBookmark()
  },
  methods: {
    push() {
      if (this.bookmarkId) {
        this.unbookmark()
      } else {
        this.bookmark()
      }
    },
    getBookmark() {
      if (this.checked) {
        this.bookmarkId = this.bookmarkIndexId
        this.bookmarkLabel = '削除'
      } else {
        fetch(
          `/api/bookmarks.json?bookmarkable_type=${this.bookmarkableType}&bookmarkable_id=${this.bookmarkableId}`,
          {
            method: 'GET',
            headers: {
              'Content-Type': 'application/json; charset=utf-8',
              'X-Requested-With': 'XMLHttpRequest',
              'X-CSRF-Token': CSRF.getToken()
            },
            credentials: 'same-origin',
            redirect: 'manual'
          }
        )
          .then((response) => {
            return response.json()
          })
          .then((json) => {
            if (json.bookmarks.length) {
              this.bookmarkId = json.bookmarks[0].id
              this.bookmarkLabel = 'Bookmark中'
            }
          })
          .catch((error) => {
            console.warn(error)
          })
      }
    },
    bookmark() {
      fetch(
        `/api/bookmarks.json?bookmarkable_type=${this.bookmarkableType}&bookmarkable_id=${this.bookmarkableId}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json; charset=utf-8',
            'X-Requested-With': 'XMLHttpRequest',
            'X-CSRF-Token': CSRF.getToken()
          },
          credentials: 'same-origin',
          redirect: 'manual'
        }
      )
        .then((response) => {
          return response.json()
        })
        .then((json) => {
          this.bookmarkId = json.id
          this.bookmarkLabel = 'Bookmark中'
          this.toast('Bookmarkしました！')
        })
        .catch((error) => {
          console.warn(error)
        })
    },
    unbookmark() {
      fetch(`/api/bookmarks/${this.bookmarkId}`, {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': CSRF.getToken()
        },
        credentials: 'same-origin',
        redirect: 'manual'
      })
        .then(() => {
          this.bookmarkId = null
          this.bookmarkLabel = 'Bookmark'
          this.toast('Bookmarkを削除しました')
        })
        .then(() => {
          this.$emit('update-index')
        })
        .catch((error) => {
          console.warn(error)
        })
    }
  }
}
</script>

<style scoped></style>
