// app/javascript/components/Check/Check.jsx
import React from 'react'
import ProductChecker from '../ProductChecker/ProductChecker'
import * as Card from '../ui/Card'
import { useCheck } from './useCheck'
import clsx from 'clsx'

const CheckComponent = ({
  emotion = null,
  checkableId,
  checkableType,
  checkableLabel,
  checkerId = null,
  checkerName = null,
  checkerAvatar = null,
  currentUserId = null
}) => {
  const {
    checkExists,
    onCreateCheck,
    onDeleteCheck
  } = useCheck(checkableId, checkableType)
  const buttonLabel = `${checkableLabel}${checkExists ? 'の確認を取り消す' : 'を確認'}`
  const isSadEmotion = emotion === 'sad'
  // TODO querySelectorを辞めてpropsから渡したい
  const hasComment =
    parseInt(document.querySelector('a[href="#comments"] > span').innerHTML) > 0
  const message = '今日の気分は「sad」ですが、コメント無しで確認しますか？'

  const handleToggleCheck = () => {
    if (checkExists) {
      onDeleteCheck()
    } else {
      if (isSadEmotion && !hasComment && !window.confirm(message)) return
      onCreateCheck()
    }
  }

  return (
    <Card.Footer className="is-only-mentor">
      {checkableType === 'Product' && (
        <Card.FooterItem className="card-main-actions__item">
          <ProductChecker
            checkerId={checkerId}
            checkerName={checkerName}
            currentUserId={currentUserId}
            productId={checkableId}
            checkableType={checkableType}
            checkerAvatar={checkerAvatar}
          />
        </Card.FooterItem>
      )}
      <Card.FooterItem className={clsx({ 'is-sub': checkExists })}>
        <button
          id="js-shortcut-check"
          className={clsx(
            'is-block',
            checkExists
              ? 'card-main-actions__muted-action'
              : 'a-button is-sm is-danger'
          )}
          onClick={handleToggleCheck}>
          {buttonLabel}
        </button>
      </Card.FooterItem>
    </Card.Footer>
  )
}

export default CheckComponent

// app/javascript/check.vue
<template>
  <div>
    <hr class="a-border-tint" />
    <div class="card-footer is-only-mentor">
      <div class="card-main-actions">
        <ul class="card-main-actions__items">
          <li
            v-if="checkableType === 'Product'"
            class="card-main-actions__item">
            <!--
              v-showではなくv-ifだと "提出物を確認" => "取り消し" した際、
              担当ボタンの表示はページ読み込み時に戻る。
              例えば、ページ読み込み時に "担当する" ボタンだった場合、
              クリックして "担当から外れる" ボタンに変更後、
              "提出物を確認" => "取り消し" すると、
              ページ読み込み時の "担当する" ボタンが表示される。
              パフォーマンスが非常に悪くなるとかではないので、今回はv-showを利用
              checkerIdの値がページ読み込み時の値のままではなく、
              現状のcheckerIdを参照すれば、v-ifでも大丈夫と推測
            -->
            <product-checker
              v-show="checkId === null"
              :checker-id="checkerId"
              :checker-name="checkerName"
              :checker-avatar="checkerAvatar"
              :current-user-id="currentUserId"
              :product-id="checkableId"
              :checkable-type="checkableType"
              :parent-component="'check'"></product-checker>
          </li>
          <li class="card-main-actions__item" :class="checkId ? 'is-sub' : ''">
            <button
              id="js-shortcut-check"
              class="is-block"
              :class="
                checkId
                  ? 'card-main-actions__muted-action'
                  : 'a-button is-sm is-danger'
              "
              @click="checkSad">
              {{ buttonLabel }}
            </button>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>
<script>
import ProductChecker from 'product_checker'
import checkable from 'checkable.js'
import { toast } from 'vanillaToast.js'

export default {
  components: {
    'product-checker': ProductChecker
  },
  mixins: [checkable],
  props: {
    checkableId: { type: Number, required: true },
    checkableType: { type: String, required: true },
    checkableLabel: { type: String, required: true },
    checkerId: { type: Number, required: true },
    checkerName: { type: String, required: false, default: null },
    checkerAvatar: { type: String, required: false, default: null },
    currentUserId: { type: Number, required: false, default: null }
  },
  computed: {
    checkId() {
      return this.$store.getters.checkId
    },
    buttonLabel() {
      const path = window.location.pathname
      if (path.includes('/products')) {
        return (
          this.checkableLabel +
          (this.checkId ? 'の合格を取り消す' : 'を合格にする')
        )
      } else {
        return (
          this.checkableLabel + (this.checkId ? 'の確認を取り消す' : 'を確認')
        )
      }
    },
    url() {
      return this.checkId ? `/api/checks/${this.checkId}` : '/api/checks'
    },
    method() {
      return this.checkId ? 'DELETE' : 'POST'
    },
    checkHasSadEmotion() {
      const sadEmotion = document.querySelector('#sad')
      return sadEmotion !== null
    },
    checkHasComment() {
      const numberOfComments = parseInt(
        document.querySelector('a[href="#comments"] > span').innerHTML
      )
      return numberOfComments > 0
    }
  },
  methods: {
    toast(...args) {
      toast(...args)
    },
    checkSad() {
      if (this.checkHasSadEmotion && !this.checkHasComment && !this.checkId) {
        if (
          window.confirm(
            '今日の気分は「sad」ですが、コメント無しで確認しますか？'
          )
        ) {
          this.check(
            this.checkableType,
            this.checkableId,
            this.url,
            this.method
          )
        }
      } else {
        this.check(this.checkableType, this.checkableId, this.url, this.method)
      }
    }
  }
}
</script>
