// app/javascript/components/Grass.jsx
import React, { useState, useEffect, useRef, forwardRef } from 'react'
import dayjs from 'dayjs'
import useSWR from 'swr'
import fetcher from '../fetcher'

const clientDateFormat = 'YYYY年M月'
const serverDateFormat = 'YYYY-MM-DD'

const GrassHeader = ({ currentUser, hideGrass }) => {
  const isDashboard = location.pathname === '/'
  return (
    <header className="card-header is-sm">
      <h2 className="card-header__title">学習時間</h2>
      {currentUser &&
        currentUser.primary_role === 'graduate' &&
        isDashboard && (
          <button
            onClick={hideGrass}
            className="a-button is-xs is-muted-bordered">
            非表示
          </button>
        )}
    </header>
  )
}

const GrassBody = ({ children }) => {
  return <div className="user-grass">{children}</div>
}

const GrassNav = ({ onAddOneYear, currentDate, onSubtractOneYear }) => {
  const prevYearMonth = dayjs(currentDate).subtract(1, 'year')
  const isLatestYearMonth = dayjs().isSame(currentDate, 'month')
  return (
    <div className="user-grass-nav">
      <div className="user-grass-nav__previous" onClick={onSubtractOneYear}>
        <i className="fa-solid fa-angle-left" />
      </div>
      <div className="user-grass-nav__year--month">
        {prevYearMonth?.format(clientDateFormat)} 〜
        {currentDate?.format(clientDateFormat)}
      </div>
      {!isLatestYearMonth ? (
        <div className="user-grass-nav__next" onClick={onAddOneYear}>
          <i className="fa-solid fa-angle-right" />
        </div>
      ) : (
        <div className="user-grass-nav__next is-blank" />
      )}
    </div>
  )
}

const GrassCanvas = forwardRef((_, ref) => {
  return (
    <canvas
      id="grass"
      className="a-grass"
      width="650px"
      height="130px"
      ref={ref}></canvas>
  )
})

export default function Grass({ currentUser, userId }) {
  const [currentDate, setCurrentDate] = useState(dayjs())
  const [isVisible, setIsVisible] = useState(true)
  const canvasRef = useRef(null)
  const formattedDate = currentDate.format(serverDateFormat)

  const { data: grasses } = useSWR(
    `/api/grasses/${userId}.json?end_date=${formattedDate}`,
    fetcher
  )

  const hideGrass = () => {
    setIsVisible(false)
  }

  useEffect(() => {
    if (grasses && canvasRef.current) {
      const render = () => {
        const startX = 16
        const startY = 20
        const height = 10
        const width = 10
        const spanX = 2
        const spanY = 2
        const ctx = canvasRef.current.getContext('2d')
        ctx.font = '8px Arial'
        ctx.strokeStyle = 'rgb(132, 132, 132)'
        ctx.clearRect(0, 0, 650, 130)

        const colors = ['#e2e5ec', '#98A5DA', '#5D72C4', '#223FAF', '#06063e']
        const dotw = ['日', '月', '火', '水', '木', '金', '土']
        for (let i = 0; i < dotw.length; i++) {
          ctx.strokeText(dotw[i], 0, startY + 8 + (height + spanY) * i)
        }

        let row = 0
        let col = 0
        let lastMonth = 0
        for (let i = 0; i < grasses.length; i++) {
          const grass = grasses[i]
          ctx.fillStyle = colors[grass.velocity]
          ctx.fillRect(
            startX + (width + spanX) * col,
            startY + (height + spanY) * row,
            width,
            height
          )

          if (row === 0) {
            const month = new Date(grass.date).getMonth() + 1
            if (lastMonth !== month) {
              ctx.strokeText(month, startX + (width + spanX) * col, startY - 10)
            }
            lastMonth = month
          }

          if (row >= 6) {
            row = 0
            col++
          } else {
            row++
          }
        }

        const lastDate = grasses[grasses.length - 1].date
        if (!dayjs(lastDate).isSame(currentDate, 'month')) {
          setCurrentDate(dayjs(lastDate))
        }

        const sampleStartX = 555
        const sampleStartY = 120
        const sampleSpanX = 3
        ctx.font = '10px Arial'
        for (let i = 0; i < colors.length; i++) {
          ctx.fillStyle = colors[i]
          ctx.fillRect(
            sampleStartX + (width + sampleSpanX) * i,
            sampleStartY,
            width,
            height
          )
        }
        ctx.strokeText('0 h', sampleStartX - 23, sampleStartY + 8.5)
        ctx.strokeText('6 h', sampleStartX + 71, sampleStartY + 8.5)
      }
      render()
    }
    document.cookie = `user_grass=${JSON.stringify(userId)}`
  }, [grasses])

  const onAddOneYear = () => {
    setCurrentDate(currentDate.add(1, 'year'))
  }

  const onSubtractOneYear = () => {
    setCurrentDate(currentDate.subtract(1, 'year'))
  }

  if (!isVisible) {
    return null
  }

  return (
    <div className="a-card">
      <GrassHeader currentUser={currentUser} hideGrass={hideGrass} />
      <hr className="a-border-tint" />
      <GrassBody>
        <GrassNav
          currentDate={currentDate}
          onAddOneYear={onAddOneYear}
          onSubtractOneYear={onSubtractOneYear}
        />
        <GrassCanvas ref={canvasRef} />
      </GrassBody>
    </div>
  )
}

// app/javascript/grass.vue
<template lang="pug">
.a-card
  header.card-header.is-sm
    h2.card-header__title
      | 学習時間
    .card-header__action(
      v-if='currentUser.primary_role === "graduate" && isDashboard')
      | <button @click='hideGrass' class='a-button is-xs is-muted-borderd'>非表示</button>
  hr.a-border-tint
  .user-grass
    .user-grass-nav
      .user-grass-nav__previous(@click='onPrevYearMonth')
        i.fa-solid.fa-angle-left
      .user-grass-nav__year--month {{ prevYearMonth && prevYearMonth.format(clientFormat) }} 〜 {{ currentYearMonth && currentYearMonth.format(clientFormat) }}
      .user-grass-nav__next(
        v-if='!isLatestYearMonth(currentYearMonth)',
        @click='onNextYearMonth')
        i.fa-solid.fa-angle-right
      .user-grass-nav__next.is-blank(v-else)
    canvas#grass.a-grass(width='650px', height='130px')
</template>

<script>
import dayjs from 'dayjs'

export default {
  props: {
    currentUser: { type: Object, required: true },
    userId: { type: String, required: true }
  },
  data() {
    return {
      clientFormat: 'YYYY年M月',
      serverFormat: 'YYYY-MM-DD',
      prevYearMonth: null,
      currentYearMonth: null
    }
  },
  computed: {
    isDashboard() {
      return location.pathname === '/'
    }
  },
  mounted() {
    this.prevYearMonth = this.getPrevYearMonth()
    this.currentYearMonth = this.getCurrentYearMonth()
    this.canvas = document.getElementById('grass')

    this.load(dayjs().format(this.serverFormat))
  },
  beforeDestroy() {
    document.cookie = `user_grass=${JSON.stringify(this.userId)}`
  },
  methods: {
    getPrevYearMonth(yearMonth) {
      return dayjs(yearMonth).subtract(1, 'year')
    },
    getCurrentYearMonth(yearMonth) {
      return dayjs(yearMonth)
    },
    isLatestYearMonth(currentYearMonth) {
      return dayjs().isSame(currentYearMonth, 'month')
    },
    onPrevYearMonth() {
      const prev = dayjs(this.currentYearMonth).subtract(1, 'year')
      this.load(prev.format(this.serverFormat))
    },
    onNextYearMonth() {
      const next = dayjs(this.currentYearMonth).add(1, 'year')
      this.load(next.format(this.serverFormat))
    },
    load(date) {
      fetch(`/api/grasses/${this.userId}.json?end_date=${date}`)
        .then((response) => {
          return response.json()
        })
        .then((json) => {
          this.render(json)
        })
        .catch((error) => {
          console.warn('parsing failed', error)
        })
    },
    render(grasses) {
      const startX = 16
      const startY = 20
      const height = 10
      const width = 10
      const spanX = 2
      const spanY = 2
      const ctx = this.canvas.getContext('2d')
      ctx.font = '8px Arial'
      ctx.strokeStyle = 'rgb(132, 132, 132)'
      ctx.clearRect(0, 0, 650, 130)

      // render day of the week
      const colors = ['#e2e5ec', '#98A5DA', '#5D72C4', '#223FAF', '#06063e']
      const dotw = ['日', '月', '火', '水', '木', '金', '土']
      for (let i = 0; i < dotw.length; i++) {
        ctx.strokeText(dotw[i], 0, startY + 8 + (height + spanY) * i)
      }

      let row = 0
      let col = 0
      let lastMonth = 0
      for (let i = 0; i < grasses.length; i++) {
        const grass = grasses[i]
        ctx.fillStyle = colors[grass.velocity]
        ctx.fillRect(
          startX + (width + spanX) * col,
          startY + (height + spanY) * row,
          width,
          height
        )

        // render month
        if (row === 0) {
          const month = new Date(grass.date).getMonth() + 1
          if (lastMonth !== month) {
            ctx.strokeText(month, startX + (width + spanX) * col, startY - 10)
          }
          lastMonth = month
        }

        if (row >= 6) {
          row = 0
          col++
        } else {
          row++
        }
      }

      const lastDate = grasses[grasses.length - 1].date
      this.prevYearMonth = this.getPrevYearMonth(lastDate)
      this.currentYearMonth = this.getCurrentYearMonth(lastDate)

      // render sample
      const sampleStartX = 555
      const sampleStartY = 120
      const sampleSpanX = 3
      ctx.font = '10px Arial'
      for (let i = 0; i < colors.length; i++) {
        ctx.fillStyle = colors[i]
        ctx.fillRect(
          sampleStartX + (width + sampleSpanX) * i,
          sampleStartY,
          width,
          height
        )
      }
      ctx.strokeText('0 h', sampleStartX - 23, sampleStartY + 8.5)
      ctx.strokeText('6 h', sampleStartX + 71, sampleStartY + 8.5)
    },
    hideGrass() {
      this.$destroy()
      this.$el.remove()
    }
  }
}
</script>
