// app/javascript/components/Notification.jsx
import React from 'react'
import dayjs from 'dayjs'
import ja from 'dayjs/locale/ja'
dayjs.locale(ja)

export default function Notification({ notification }) {
  const createdAt = dayjs(notification.created_at).format(
    'YYYY年MM月DD日(ddd) HH:mm'
  )
  const roleClass = `is-${notification.sender.primary_role}`

  // const [formattedCreatedAt, setFormattedCreatedAt] = useState(
  //   formatCreatedAtInJapanese
  // )

  return (
    <div
      className={`card-list-item ${
        notification.read ? 'is-read' : 'is-unread'
      }`}>
      <div className="card-list-item__inner">
        <div className="card-list-item__user">
          <img
            className={`card-list-item__user-icon a-user-icon ${roleClass}`}
            title={notification.sender.icon_title}
            src={notification.sender.avatar_url}
          />
        </div>
        <div className="card-list-item__rows">
          <div className="card-list-item__row">
            <div className="card-list-item-title">
              <div className="card-list-item-title__start">
                {notification.read === false && (
                  <div className="a-list-item-badge is-unread">
                    <span>未読</span>
                  </div>
                )}
                <h2 className="card-list-item-title__title" itemProp="name">
                  <a
                    className="card-list-item-title__link a-text-link js-unconfirmed-link"
                    href={notification.path}
                    itemProp="url">
                    <span className="card-list-item-title__link-label">
                      {notification.message}
                    </span>
                  </a>
                </h2>
              </div>
            </div>
          </div>
          <div className="card-list-item__row">
            <div className="card-list-item-meta">
              <div className="card-list-item-meta__items">
                <div className="card-list-item-meta__item">
                  <time className="a-meta" dateTime={notification.created_at}>
                    {createdAt}
                  </time>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// app/javascript/notification.vue
<template lang="pug">
.card-list-item(:class='notification.read ? "is-read" : "is-unread"')
  .card-list-item__inner
    .card-list-item__user
      img.card-list-item__user-icon.a-user-icon(
        :title='notification.sender.icon_title',
        :src='notification.sender.avatar_url',
        :class='[roleClass]'
      )
    .card-list-item__rows
      .card-list-item__row
        .card-list-item-title
          .card-list-item-title__start
            .a-list-item-badge.is-unread(
              v-if='notification.read === false'
            )
              span
                | 未読
            h2.card-list-item-title__title(itemprop='name')
              a.card-list-item-title__link.a-text-link.js-unconfirmed-link(
                :href='notification.path',
                itemprop='url'
              )
                span.card-list-item-title__link-label
                  | {{ notification.message }}
      .card-list-item__row
        .card-list-item-meta
          .card-list-item-meta__items
            .card-list-item-meta__item
              time.a-meta(:datetime='notification.created_at')
                | {{ formattedCreatedAtInJapanese }}
</template>
<script>
import dayjs from 'dayjs'
import ja from 'dayjs/locale/ja'
dayjs.locale(ja)

export default {
  props: {
    notification: { type: Object, required: true }
  },
  computed: {
    formattedCreatedAtInJapanese() {
      return dayjs(this.notification.created_at).format(
        'YYYY年MM月DD日(ddd) HH:mm'
      )
    },
    roleClass() {
      return `is-${this.notification.sender.primary_role}`
    }
  }
}
</script>
