// app/javascript/components/Products.jsx
import React from 'react'
import useSWR from 'swr'
import Pagination from './Pagination'
import LoadingListPlaceholder from './LoadingListPlaceholder'
import UnconfirmedLink from './UnconfirmedLink'
import Product from './Product'
import fetcher from '../fetcher'
import ElapsedDays from './ElapsedDays'
import usePage from './hooks/usePage'

export default function Products({
  title,
  selectedTab,
  checkerId,
  isMentor,
  currentUserId
}) {
  const per = 50
  const { page, setPage } = usePage()

  const unconfirmedLinksName = () => {
    if (selectedTab === 'all') return '全ての提出物を一括で開く'
    if (selectedTab === 'unchecked') return '未完了の提出物を一括で開く'
    if (selectedTab === 'unassigned') return '未アサインの提出物を一括で開く'
    if (selectedTab === 'self_assigned') return '自分の担当の提出物を一括で開く'
  }

  const path = () => {
    if (selectedTab === 'all') return ''
    if (selectedTab === 'unassigned') return '/unassigned'
    if (selectedTab === 'unchecked') return '/unchecked'
    if (selectedTab === 'self_assigned') return '/self_assigned'
  }

  const ApiUrl = () => {
    const params = new URLSearchParams(location.search)
    const buildedUrl =
      '/api/products' +
      path() +
      '.json' +
      '?' +
      params +
      (checkerId ? `&checker_id=${checkerId}` : '') +
      (params.target ? `&target=${params.target}` : '') +
      `&per=${per}`
    return buildedUrl
  }

  const isDashboard = () => {
    return location.pathname === '/'
  }

  const { data, error } = useSWR(ApiUrl(), fetcher)

  const getElementNdaysPassed = (elapsedDays, productsGroupedByElapsedDays) => {
    const element = productsGroupedByElapsedDays.find(
      (el) => el.elapsed_days === elapsedDays
    )
    return element
  }

  const countProductsGroupedBy = (elapsedDays) => {
    const element = getElementNdaysPassed(
      elapsedDays,
      data.products_grouped_by_elapsed_days
    )
    return element === undefined ? 0 : element.products.length
  }

  const isNotProduct5daysElapsed = () => {
    const elapsedDays = []
    data.productsGroupedByElapsedDays.forEach((h) => {
      elapsedDays.push(h.elapsed_days)
    })
    return elapsedDays.every((day) => day < 5)
  }
  const elapsedDaysId = (elapsedDays) => {
    return `${elapsedDays}days-elapsed`
  }

  function ProductHeader({ productsNDaysPassed }) {
    let headerClass = 'card-header a-elapsed-days'
    if (productsNDaysPassed.elapsed_days === 5) {
      headerClass += ' is-reply-warning'
    } else if (productsNDaysPassed.elapsed_days === 6) {
      headerClass += ' is-reply-alert'
    } else if (productsNDaysPassed.elapsed_days >= 7) {
      headerClass += ' is-reply-deadline'
    }

    const headerLabel = () => {
      if (productsNDaysPassed.elapsed_days === 0) {
        return '今日提出'
      } else if (productsNDaysPassed.elapsed_days === 7) {
        return `${productsNDaysPassed.elapsed_days}日以上経過`
      } else {
        return `${productsNDaysPassed.elapsed_days}日経過`
      }
    }

    return (
      <header
        className={headerClass}
        id={elapsedDaysId(productsNDaysPassed.elapsed_days)}>
        <h2 className="card-header__title">
          {headerLabel()}
          {
            <span className="card-header__count">
              （{countProductsGroupedBy(productsNDaysPassed.elapsed_days)}）
            </span>
          }
        </h2>
      </header>
    )
  }

  if (error) return <>エラーが発生しました。</>

  if (!data) {
    return (
      <div className="page-body">
        <div className="container is-md">
          <LoadingListPlaceholder />
        </div>
      </div>
    )
  } else if (data.products.length === 0) {
    return (
      <div class="o-empty-message">
        <div class="o-empty-message__icon">
          <i class="fa-regular fa-smile"></i>
        </div>
        <p class="o-empty-message__text">{title}はありません</p>
      </div>
    )
  } else if (isDashboard() && isNotProduct5daysElapsed()) {
    return (
      <div className="o-empty-message">
        <div className="o-empty-message__icon">
          <i className="fa-regular fa-smile" />
        </div>
        <p className="o-empty-message__text">5日経過した提出物はありません</p>
      </div>
    )
  } else if (selectedTab !== 'unassigned') {
    return (
      <>
        <div className="page-content is-products">
          <div className="page-body__columns">
            <div className="page-body__column is-main">
              <div className="container is-md">
                {data.total_pages > 1 && (
                  <Pagination
                    sum={data.total_pages * per}
                    per={per}
                    page={page}
                    setPage={setPage}
                  />
                )}
                <ul className="card-list a-card">
                  {data.products.map((product) => {
                    return (
                      <Product
                        product={product}
                        key={product.id}
                        isMentor={isMentor}
                        currentUserId={currentUserId}
                      />
                    )
                  })}
                </ul>
                {data.total_pages > 1 && (
                  <Pagination
                    sum={data.total_pages * per}
                    per={per}
                    page={page}
                    setPage={setPage}
                  />
                )}
                <UnconfirmedLink label={unconfirmedLinksName()} />
              </div>
            </div>
          </div>
        </div>
      </>
    )
  } else {
    return (
      <div className="page-content is-products">
        <div className="page-body__columns">
          <div className="page-body__column is-main">
            {data.products_grouped_by_elapsed_days.map(
              (productsNDaysPassed) => {
                return (
                  <div
                    className="a-card"
                    key={productsNDaysPassed.elapsed_days}>
                    <ProductHeader productsNDaysPassed={productsNDaysPassed} />
                    <div className="card-list">
                      <div className="card-list__items">
                        {productsNDaysPassed.products.map((product) => {
                          return (
                            <Product
                              product={product}
                              key={product.id}
                              isMentor={isMentor}
                              currentUserId={currentUserId}
                            />
                          )
                        })}
                      </div>
                    </div>
                  </div>
                )
              }
            )}
            <UnconfirmedLink label={unconfirmedLinksName()} />
          </div>

          <ElapsedDays
            productsGroupedByElapsedDays={data.products_grouped_by_elapsed_days}
            countProductsGroupedBy={countProductsGroupedBy}
          />
        </div>
      </div>
    )
  }
}

// app/javascript/products.vue
<template lang="pug">
.page-content(v-if='!loaded')
  loadingListPlaceholder
.o-empty-message(v-else-if='products.length === 0')
  .o-empty-message__icon
    i.fa-regular.fa-smile
  p.o-empty-message__text
    | {{ title }}はありません
.o-empty-message(v-else-if='isDashboard && isNotProduct5daysElapsed')
  .o-empty-message__icon
    i.fa-regular.fa-smile
  p.o-empty-message__text
    | 5日経過した提出物はありません
div(:class='contentClassName')(v-else)
  nav.pagination(v-if='totalPages > 1')
    pager(v-bind='pagerProps')
  div(:class='columnsClassName')
    div(:class='columnClassName')
      .a-card(v-if='productsGroupedByElapsedDays === null')
        .card-list
          .card-list__items
            product(
              v-for='product in products',
              :key='product.id',
              :product='product',
              :currentUserId='currentUserId',
              :isMentor='isMentor')
      template(v-for='product_n_days_passed in productsGroupedByElapsedDays') <!-- product_n_days_passedはn日経過の提出物 -->
        .a-card(:class='cardClassName')(
          v-if='!isDashboard || (isDashboard && product_n_days_passed.elapsed_days >= 5)')
          //- prettier-ignore: need space between v-if and id
          header.card-header.a-elapsed-days(
            v-if='product_n_days_passed.elapsed_days === 0', id='0days-elapsed'
          )
            h2.card-header__title
              | 今日提出
              span.card-header__count(v-if='selectedTab === "unassigned"')
                | （{{ countProductsGroupedBy(product_n_days_passed) }}）
          //- prettier-ignore: need space between v-else-if and id
          header.card-header.a-elapsed-days.is-reply-warning(
            v-else-if='product_n_days_passed.elapsed_days === 5', id='5days-elapsed'
          )
            h2.card-header__title
              | {{ product_n_days_passed.elapsed_days }}日経過
              span.card-header__count(v-if='selectedTab === "unassigned"')
                | （{{ countProductsGroupedBy(product_n_days_passed) }}）
          //- prettier-ignore: need space between v-else-if and id
          header.card-header.a-elapsed-days.is-reply-alert(
            v-else-if='product_n_days_passed.elapsed_days === 6', id='6days-elapsed'
          )
            h2.card-header__title
              | {{ product_n_days_passed.elapsed_days }}日経過
              span.card-header__count(v-if='selectedTab === "unassigned"')
                | （{{ countProductsGroupedBy(product_n_days_passed) }}）
          //- prettier-ignore: need space between v-else-if and id
          header.card-header.a-elapsed-days.is-reply-deadline(
            v-else-if='product_n_days_passed.elapsed_days === 7', id='7days-elapsed'
          )
            h2.card-header__title
              | {{ product_n_days_passed.elapsed_days }}日以上経過
              span.card-header__count(v-if='selectedTab === "unassigned"')
                | （{{ countProductsGroupedBy(product_n_days_passed) }}）
          header.card-header.a-elapsed-days(
            v-else,
            :id='elapsedDaysId(product_n_days_passed.elapsed_days)')
            h2.card-header__title
              | {{ product_n_days_passed.elapsed_days }}日経過
              span.card-header__count(v-if='selectedTab === "unassigned"')
                | （{{ countProductsGroupedBy(product_n_days_passed) }}）
          .card-list
            .card-list__items
              product(
                v-for='product in product_n_days_passed.products',
                :key='product.id',
                :product='product',
                :currentUserId='currentUserId',
                :isMentor='isMentor')
      unconfirmed-links-open-button(
        v-if='isMentor && selectedTab != "all" && !isDashboard',
        :label='`${unconfirmedLinksName}の提出物を一括で開く`')
    elapsedDays(
      v-if='!isDashboard && selectedTab === "unassigned"',
      :productsGroupedByElapsedDays='productsGroupedByElapsedDays',
      :countProductsGroupedBy='countProductsGroupedBy')
  nav.pagination(v-if='totalPages > 1')
    pager(v-bind='pagerProps')
</template>

<script>
import Product from 'product.vue'
import UnconfirmedLinksOpenButton from 'unconfirmed_links_open_button.vue'
import LoadingListPlaceholder from 'loading-list-placeholder.vue'
import Pager from 'pager.vue'
import ElapsedDays from 'elapsed_days.vue'

export default {
  components: {
    product: Product,
    'unconfirmed-links-open-button': UnconfirmedLinksOpenButton,
    loadingListPlaceholder: LoadingListPlaceholder,
    pager: Pager,
    elapsedDays: ElapsedDays
  },
  props: {
    title: { type: String, required: true },
    selectedTab: { type: String, required: true },
    isMentor: { type: Boolean, required: true },
    currentUserId: { type: String, required: true },
    checkerId: { type: String, required: false, default: null }
  },
  data() {
    return {
      products: [],
      totalPages: 0,
      currentPage: Number(this.getPageValueFromParameter()) || 1,
      loaded: false,
      productsGroupedByElapsedDays: null,
      params: this.getParams()
    }
  },
  computed: {
    url() {
      return (
        '/api/products' +
        (this.selectedTab === 'all'
          ? ''
          : '/' + this.selectedTab.replace('-', '_')) +
        `?page=${this.currentPage}` +
        (this.checkerId ? `&checker_id=${this.checkerId}` : '') +
        (this.params.target ? `&target=${this.params.target}` : '')
      )
    },
    unconfirmedLinksName() {
      return {
        unchecked: '未完了',
        'self-assigned': '自分の担当',
        unassigned: '未アサイン'
      }[this.selectedTab]
    },
    pagerProps() {
      return {
        initialPageNumber: this.currentPage,
        pageCount: this.totalPages,
        pageRange: 5,
        clickHandle: this.paginateClickCallback
      }
    },
    contentClassName() {
      return this.isDashboard ? 'block' : 'page-content is-products'
    },
    columnsClassName() {
      return this.isDashboard ? 'block' : 'page-body__columns'
    },
    columnClassName() {
      return this.isDashboard ? 'block' : 'page-body__column is-main'
    },
    cardClassName() {
      return this.isDashboard ? 'h-auto' : ''
    },
    isDashboard() {
      return location.pathname === '/'
    },
    isNotProduct5daysElapsed () {
      const elapsedDays = []
      this.productsGroupedByElapsedDays.forEach((h) => {
        elapsedDays.push(h.elapsed_days)
      })
      return elapsedDays.every((day) => day < 5)
    }
  },
  created() {
    window.onpopstate = () => {
      this.currentPage = Number(this.getPageValueFromParameter()) || 1
      this.getProductsPerPage()
    }
    this.getProductsPerPage()
  },
  methods: {
    token() {
      const meta = document.querySelector('meta[name="csrf-token"]')
      return meta ? meta.getAttribute('content') : ''
    },
    getProductsPerPage() {
      fetch(this.url, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': this.token()
        },
        credentials: 'same-origin',
        redirect: 'manual'
      })
        .then((response) => {
          return response.json()
        })
        .then((json) => {
          if (
            location.pathname === '/products/unassigned' ||
            location.pathname === '/products/unchecked' ||
            location.pathname === '/'
          ) {
            this.productsGroupedByElapsedDays =
              json.products_grouped_by_elapsed_days
          }
          this.totalPages = json.total_pages
          this.products = []
          json.products.forEach((product) => {
            this.products.push(product)
          })
          this.loaded = true
        })
        .then(() => {
          const hash = location.hash.slice(1)
          const element = document.getElementById(hash)
          if (element) {
            element.scrollIntoView()
          }
        })
        .catch((error) => {
          console.warn(error)
        })
    },
    getPageValueFromParameter() {
      const url = location.href
      const results = url.match(/\?page=(\d+)/)
      if (!results) return null
      return results[1]
    },
    paginateClickCallback(pageNumber) {
      this.currentPage = pageNumber
      this.getProductsPerPage()
      history.pushState(null, null, this.newUrl(pageNumber))
      window.scrollTo(0, 0)
    },
    newUrl(pageNumber) {
      const params = new URL(location.origin).searchParams
      if (pageNumber !== 1) params.set('page', pageNumber)
      if (this.params.target) params.set('target', this.params.target)
      if (this.params.checker_id)
        params.set('checker_id', this.params.checker_id)
      if (
        params.get('page') ||
        params.get('target') ||
        params.get('checker_id')
      )
        return `${location.pathname}?${params}`
      return location.pathname
    },
    getParams() {
      const params = {}
      location.search
        .slice(1)
        .split('&')
        .forEach((query) => {
          const queryArr = query.split('=')
          params[queryArr[0]] = queryArr[1]
        })
      return params
    },
    countProductsGroupedBy({ elapsed_days: elapsedDays }) {
      const element = this.productsGroupedByElapsedDays.find(
        (el) => el.elapsed_days === elapsedDays
      )
      return element === undefined ? 0 : element.products.length
    },
    elapsedDaysId(elapsedDays) {
      return `${elapsedDays}days-elapsed`
    }
  }
}
</script>
