// app/javascript/components/ProductChecker.jsx
import React, { useState } from 'react'
import CSRF from 'csrf'
import { checkProduct } from './Checkable.jsx'

export default function ProductChecker({
  checkerId,
  checkerName,
  currentUserId,
  productId,
  checkableType,
  checkerAvatar
}) {
  const [isCheckerExist, setisCheckerExist] = useState(checkerId)

  const buttonLabel = () => (isCheckerExist ? '担当から外れる' : '担当する')

  const checkInCharge = () => {
    checkProduct(
      productId,
      currentUserId,
      '/api/products/checker',
      isCheckerExist ? 'DELETE' : 'PATCH',
      CSRF.getToken()
    )
  }
  return (
    <>
      {(!checkerId || checkerId === currentUserId) && (
        <button
          className={`a-button is-block ${
            isCheckerExist ? 'is-warning' : 'is-secondary'
          } ${checkableType ? 'is-sm' : 'is-sm'} `}
          onClick={() => {
            setisCheckerExist(!isCheckerExist)
            checkInCharge()
          }}>
          <i
            className={`fas ${isCheckerExist ? 'fa-times' : 'fa-hand-paper'}`}
          />
          {buttonLabel()}
        </button>
      )}
      {checkerId && checkerId !== currentUserId && (
        <div className="a-button is-sm is-block card-list-item__assignee-button is-only-mentor">
          <span className="card-list-item__assignee-image">
            <img
              className="a-user-icon"
              src={checkerAvatar}
              width="20"
              height="20"
              alt="Checker Avatar"
            />
          </span>
          <span className="card-list-item__assignee-name">{checkerName}</span>
        </div>
      )}
    </>
  )
}

// app/javascript/product_checker.vue
<template lang="pug">
button(
  v-if='!checkerId || checkerId === currentUserId',
  :class='["a-button", "is-block", productCheckerId ? "is-warning" : "is-secondary", checkableType ? "is-sm" : "is-sm"]',
  @click='checkInCharge')
  i(
    v-if='!checkerId || checkerId === currentUserId',
    :class='["fas", productCheckerId ? "fa-times" : "fa-hand-paper"]',
    @click='checkInCharge')
  | {{ buttonLabel }}
.a-button.is-sm.is-block.card-list-item__assignee-button.is-only-mentor(v-else)
  span.card-list-item__assignee-image
    img.a-user-icon(:src='checkerAvatar', width='20', length='20')
  span.card-list-item__assignee-name
    | {{ this.name }}
</template>
<script>
import { toast } from 'vanillaToast'
import checkable from './checkable.js'

export default {
  mixins: [checkable],
  props: {
    checkerId: { type: Number, required: false, default: null },
    checkerName: { type: String, required: false, default: null },
    currentUserId: { type: Number, required: true },
    productId: { type: Number, required: true },
    checkableType: { type: String, required: false, default: null },
    checkerAvatar: { type: String, required: false, default: null },
    parentComponent: { type: String, required: true }
  },
  data() {
    return {
      id: this.checkerId,
      name: this.checkerName,
      parent: this.parentComponent,
      forceUpdate: false
    }
  },
  computed: {
    productCheckerId() {
      if (this.parent === 'product') {
        return this.id
      } else {
        return this.$store.getters.productCheckerId
      }
    },
    buttonLabel() {
      return this.productCheckerId ? '担当から外れる' : '担当する'
    },
    url() {
      return `/api/products/checker`
    }
  },
  mounted() {
    this.$store.dispatch('setProduct', {
      productId: this.productId
    })

    window.addEventListener('checkerAssigned', this.handleCheckerAssigned)
  },
  beforeDestroy() {
    window.removeEventListener('checkerAssigned', this.handleCheckerAssigned)
  },
  methods: {
    toast(...args) {
      toast(...args)
    },
    checkInCharge() {
      this.checkProduct(
        this.productId,
        this.currentUserId,
        '/api/products/checker',
        this.productCheckerId ? 'DELETE' : 'PATCH',
        false
      )
    },
    handleCheckerAssigned() {
      this.parent = 'product'
      this.id = this.currentUserId
    }
  }
}
</script>
