// app/javascript/components/Report.jsx
import React from 'react'
import CommentUserIcon from './CommentUserIcon'

export default function Report({report, currentUser}){
  return (
    <div className={`card-list-item ${report.wip ? "is-wip" : ""}`}>
      <div className="card-list-item__inner">
        <div className="card-list-item__user">
          <a href={report.user.url} className="card-list-item__user-link">
            <span className="[&quot;a-user-role&quot;, roleClass]">
              <img className="card-list-item__user-icon a-user-icon" src={report.user.avatar_url} title={report.user.login_name} alt={report.user.login_name} />
            </span>
          </a>
        </div>
        <div className="card-list-item__rows">
          <div className="card-list-item__row">
            <header className="card-list-item-title">
              <div className="card-list-item-title__start">
                {report.wip && (
                  <div className="a-list-item-badge is-wip">
                    <span>WIP</span>
                  </div>
                )}
                <h2 className="card-list-item-title__title">
                  <a className="card-list-item-title__link a-text-link js-unconfirmed-link" href={report.url}>
                    <img className="card-list-item-title__emotion-image" src={`/images/emotion/${report.emotion}.svg`} alt={report.emotion} />
                    {report.title}
                  </a>
                </h2>
                {(currentUser.id === report.user.id) && (
                  <ReportListItemActions report={report} />
                )}
              </div>
            </header>
          </div>
          <div className="card-list-item__row">
            <div className="card-list-item-meta">
              <div className="card-list-item-meta__items">
                <div className="card-list-item-meta__item">
                  <a className="a-user-name" href={report.user.url}>
                    { report.user.long_name }
                  </a>
                </div>
                <div className="card-list-item-meta__item">
                  <time className="a-meta">{ `${report.reportedOn}の日報` }</time>
                </div>
              </div>
            </div>
          {(report.hasAnyComments) && (
            <ReportListComment report={report} />
          )}
          </div>
        </div>
        {report.hascheck && (
          <div className="stamp stamp-approve">
            <h2 className="stamp__content is-title">確認済</h2>
            <time className="stamp__content is-created-at">{ report.checkDate }</time>
            <div className="stamp__content is-user-name">
              <div className="stamp__content-inner">{ report.checkUserName }</div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

const ReportListItemActions = ({ report }) => {
  return (
    <div className="card-list-item-title__end">
      <label className="card-list-item-actions__trigger" for={report.id}></label>
      <div className="card-list-item-actions">
        <input className="a-toggle-checkbox" type="checkbox" id={report.id} />
        <div className="card-list-item-actions__inner">
          <ul>
            <li className="card-list-item-actions__item">
              <a className="card-list-item-actions__action" href={report.editURL}>
                <i className="fa-solid fa-pen">内容変更</i>
              </a>
            </li>
            <li className="card-list-item-actions__item">
              <a className="card-list-item-actions__action" href={report.newURL}>
                <i className="fa-solid fa-copy">コピー</i>
              </a>
            </li>
          </ul>
          <label className="a-overlay" for={report.id}></label>
        </div>
      </div>
    </div>
  )
}

const ReportListComment = ({ report }) => {
  return (
    <>
      <hr className="card-list-item__row-separator"></hr>
      <div className="card-list-item__row">
        <div className="card-list-item-meta">
          <div className="card-list-item-meta__items">
            <div className="card-list-item-meta__item">
              <div className="a-meta">コメント（{ report.numberOfComments }）</div>
            </div>
            <div className="card-list-item-meta__item">
              <div className="card-list-item__user-icons">
                {report.comments.map((comment) => {
                  return (
                    <CommentUserIcon comment={comment} key={comment.user_id}/>
                  )
                })}
              </div>
            </div>
            <div className="card-list-item-meta__item">
              <time className="a-meta" dateTime={report.lastCommentDatetime} pubdate="'pubdate'">{`〜 ${report.lastCommentDate}`}</time>
            </div>
            <div className="card-list-item-meta__item"></div>
          </div>
        </div>
      </div>
    </>
  )
}

// app/javascript/report.vue
<template lang="pug">
.card-list-item(:class='wipClass')
  .card-list-item__inner
    .card-list-item__user
      a.card-list-item__user-link(:href='report.user.url')
        img.card-list-item__user-icon.a-user-icon(
          :src='report.user.avatar_url',
          :title='report.user.login_name',
          :alt='report.user.login_name',
          :class='[roleClass]'
        )
    .card-list-item__rows
      .card-list-item__row
        header.card-list-item-title
          .card-list-item-title__start
            .card-list-item-title__icon.is-wip(v-if='report.wip') WIP
            h2.card-list-item-title__title
              a.card-list-item-title__link.a-text-link.js-unconfirmed-link(
                :href='report.url'
              ) {{ report.title }}
            .card-list-item-title__end(v-if='currentUserId == report.user.id')
              label.card-list-item-actions__trigger(:for='report.id')
                i.fa-solid.fa-ellipsis-h
              .card-list-item-actions
                input.a-toggle-checkbox(type='checkbox', :id='report.id')
                .card-list-item-actions__inner
                  ul.card-list-item-actions__items
                    li.card-list-item-actions__item
                      a.card-list-item-actions__action(:href='report.editURL')
                        i.fa-solid.fa-pen
                        | 内容変更
                    li.card-list-item-actions__item
                      a.card-list-item-actions__action(:href='report.newURL')
                        i.fa-solid.fa-copy
                        | コピー
                  label.a-overlay(:for='report.id')

      .card-list-item__row
        .card-list-item-meta
          .card-list-item-meta__items
            .card-list-item-meta__item
              a.a-user-name(:href='report.user.url') {{ report.user.long_name }}
            .card-list-item-meta__item
              time.a-meta
                | {{ report.reportedOn }}の日報
      hr.card-list-item__row-separator(v-if='report.hasAnyComments')
      .card-list-item__row(v-if='report.hasAnyComments')
        .card-list-item-meta
          .card-list-item-meta__items
            .card-list-item-meta__item
              .a-meta
                | コメント（{{ report.numberOfComments }}）
            .card-list-item-meta__item
              .card-list-item-comment__user-icons
                comment-user-icon(
                  v-for='comment in report.comments',
                  :key='comment.id',
                  :comment='comment'
                )
            .card-list-item-meta__item
              time.a-meta(
                datetime='report.lastCommentDatetime',
                pubdate='\'pubdate\''
              )
                | 〜 {{ report.lastCommentDate }}
    .stamp.stamp-approve(v-if='this.report.hasCheck')
      h2.stamp__content.is-title
        | 確認済
      time.stamp__content.is-created-at
        | {{ report.checkDate }}
      .stamp__content.is-user-name
        .stamp__content-inner
          | {{ report.checkUserName }}
</template>

<script>
import CommentUserIcon from 'comment-user-icon.vue'

export default {
  components: {
    'comment-user-icon': CommentUserIcon
  },
  props: {
    report: { type: Object, required: true },
    currentUserId: { type: Number, required: true }
  },
  computed: {
    roleClass() {
      return `is-${this.report.user.primary_role}`
    },
    wipClass() {
      return { 'is-wip': this.report.wip }
    }
  }
}
</script>
