// app/javascript/components/Searchables.jsx
import React from 'react'
import useSWR from 'swr'
import usePage from './hooks/usePage'
import Pagination from './Pagination'
import LoadingListPlaceholder from './LoadingListPlaceholder'
import Searchable from './Searchable'
import fetcher from '../fetcher'

export default function Searchables({ word }) {
  const per = 50
  const { page, setPage } = usePage()
  const params = new URLSearchParams(location.search)
  const url = `/api/searchables.json?${params}`
  const { data, error } = useSWR(url, fetcher)

  if (error) {
    console.warn(error)
    return <div>failed to load</div>
  }

  return (
    <div className="page-body">
      {!data && (
        <div className="container is-md">
          <LoadingListPlaceholder />
        </div>
      )}

      {data?.searchables.length === 0 && (
        <div className="container">
          <div className="o-empty-message">
            <div className="o-empty-message__icon">
              <i className="fa-regular fa-sad-tear" />
            </div>
            <p className="o-empty-message__text">
              {word}に一致する情報は見つかりませんでした。
            </p>
          </div>
        </div>
      )}

      {data && data.searchables.length > 0 && (
        <div className="container is-md">
          {data.total_pages > 1 && (
            <nav className="pagination">
              <Pagination
                sum={data.total_pages * per}
                per={per}
                neighbours={2}
                page={page}
                setPage={setPage}
              />
            </nav>
          )}
          <div className="card-list a-card">
            {data.searchables.map((searchable) => (
              <Searchable
                key={searchable.url}
                searchable={searchable}
                word={word}
              />
            ))}
          </div>
          {data.total_pages > 1 && (
            <nav className="pagination">
              <Pagination
                sum={data.total_pages * per}
                per={per}
                neighbours={2}
                page={page}
                setPage={setPage}
              />
            </nav>
          )}
        </div>
      )}
    </div>
  )
}

// app/javascript/searchables.vue
<template lang="pug">
.page-body
  .container.is-md(v-if='!loaded')
    loadingListPlaceholder
  .container(v-else-if='searchables.length === 0')
    .o-empty-message
      .o-empty-message__icon
        i.fa-regular.fa-sad-tear
      p.o-empty-message__text
        | '{{ word }}'に一致する情報は見つかりませんでした。
  .container.is-md(v-else)
    nav.pagination(v-if='totalPages > 1')
      pager(v-bind='pagerProps')
    .card-list.a-card
      searchable(
        v-for='searchable in searchables',
        :key='searchable.id',
        :searchable='searchable',
        :word='word')
    nav.pagination(v-if='totalPages > 1')
      pager(v-bind='pagerProps')
</template>

<script>
import CSRF from 'csrf'
import LoadingListPlaceholder from 'loading-list-placeholder.vue'
import Pager from 'pager.vue'
import Searchable from 'searchable.vue'

export default {
  components: {
    searchable: Searchable,
    loadingListPlaceholder: LoadingListPlaceholder,
    pager: Pager
  },
  props: {
    documentType: { type: String, required: true },
    word: { type: String, required: true }
  },
  data() {
    return {
      searchables: [],
      totalPages: 0,
      currentPage: Number(this.getPageValueFromParameter()) || 1,
      loaded: false
    }
  },
  computed: {
    url() {
      const params = new URLSearchParams()
      params.append('document_type', this.documentType)
      params.append('page', this.currentPage)
      params.append('word', this.word)
      return `/api/searchables?${params}`
    },
    pagerProps() {
      return {
        initialPageNumber: this.currentPage,
        pageCount: this.totalPages,
        pageRange: 5,
        clickHandle: this.paginateClickCallback
      }
    }
  },
  created() {
    window.onpopstate = function () {
      location.replace(location.href)
    }
    this.getSearchablesPerPage()
  },
  methods: {
    getSearchablesPerPage() {
      fetch(this.url, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': CSRF.getToken()
        },
        credentials: 'same-origin',
        redirect: 'manual'
      })
        .then((response) => {
          return response.json()
        })
        .then((json) => {
          this.totalPages = json.total_pages
          this.searchables = []
          json.searchables.forEach((searchable) => {
            this.searchables.push(searchable)
          })
          this.loaded = true
        })
        .catch((error) => {
          console.warn(error)
        })
    },
    getPageValueFromParameter() {
      const url = location.href
      const results = url.match(/page=(\d+)/)
      if (!results) return null
      return results[1]
    },
    paginateClickCallback(pageNumber) {
      this.currentPage = pageNumber
      this.getSearchablesPerPage()
      history.pushState(
        null,
        null,
        location.pathname +
          `?document_type=${this.documentType}` +
          (pageNumber === 1 ? '' : `&page=${pageNumber}`) +
          `&word=${this.word}`
      )
      window.scrollTo(0, 0)
    }
  }
}
</script>
