// app/javascript/components/Tags/TagEditModal.jsx
import React, { useState } from 'react';
import toast from "../../toast";

export default function TagEditModal ({ tagId, propTagName, setShowModal }) {
  const initialTagName = propTagName;
  const [tagName, setTagName] = useState(propTagName);

  const validation = tagName === initialTagName || tagName === '';

  const token = () => {
    const meta = document.querySelector('meta[name="csrf-token"]');
    return meta ? meta.getAttribute('content') : '';
  };

  const changeTagName = (e) => {
    setTagName(e.target.value)
  };

  const closeModal = () => {
    setShowModal(false);
    setTagName(initialTagName)
  };

  const updateTagList = () => {
    toast.methods.toast('タグ名を変更しました');
    const url = location.pathname.split('/');
    const path = url[url.length - 3];
    location.href = `/${path}/tags/${encodeURIComponent(tagName)}?all=true`;
  };

  const updateTag = () => {
    if (tagName === '' || tagName === initialTagName) {
      return null;
    }

    const params = {
      tag: { name: tagName }
    };

    fetch(`/api/tags/${tagId}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
        'X-Requested-With': 'XMLHttpRequest',
        'X-CSRF-Token': token()
      },
      credentials: 'same-origin',
      redirect: 'manual',
      body: JSON.stringify(params)
    })
      .then(() => {
        setTagName(tagName)
        closeModal();
        updateTagList();
      })
      .catch((error) => {
        console.warn(error);
      });
  };

  return (
    <div className="a-overlay is-vue" onClick={(e) => e.target === e.currentTarget && closeModal()}>
      <div className="a-card is-modal">
        <header className="card-header is-sm">
          <h2 className="card-header__title">タグ名変更</h2>
        </header>
        <div className="card-body">
          <div className="card__description">
            <label className="a-form-label" htmlFor="tag_name">
              タグ名
            </label>
            <input
              id="tag_name"
              className="a-text-input"
              value={tagName}
              onChange={changeTagName}
              name="tag[name]"
            />
          </div>
        </div>
        <footer className="card-footer">
          <div className="card-main-actions">
            <ul className="card-main-actions__items">
              <li className="card-main-actions__item is-main">
                <button
                  className="a-button is-primary is-sm is-block"
                  disabled={validation}
                  onClick={updateTag}
                >
                  変更
                </button>
              </li>
              <li className="card-main-actions__item is-sub">
                <div className="card-main-actions__muted-action" onClick={closeModal}>
                  キャンセル
                </div>
              </li>
            </ul>
          </div>
        </footer>
      </div>
    </div>
  );
};

// app/javascript/tag-edit-modal.vue
<template lang="pug">
.a-overlay.is-vue(@click.self='closeModal')
  .a-card.is-modal
    header.card-header.is-sm
      h2.card-header__title
        | タグ名変更
    .card-body
      .card__description
        label.a-form-label(for='tag_name')
          | タグ名
        input#tag_name.a-text-input(v-model='name', name='tag[name]')
    footer.card-footer
      .card-main-actions
        ul.card-main-actions__items
          li.card-main-actions__item.is-main
            button.a-button.is-primary.is-sm.is-block(
              :disabled='validation',
              @click.prevent='updateTag')
              | 変更
          li.card-main-actions__item.is-sub
            .card-main-actions__muted-action(@click.prevent='closeModal')
              | キャンセル
</template>
<script>
export default {
  props: {
    id: { type: String, required: true },
    nameProp: { type: String, required: true }
  },
  data() {
    return {
      name: '',
      initialName: ''
    }
  },
  computed: {
    validation() {
      return this.name === this.initialName || this.name === ''
    }
  },
  mounted() {
    this.name = this.nameProp
    this.initialName = this.nameProp
  },
  methods: {
    token() {
      const meta = document.querySelector('meta[name="csrf-token"]')
      return meta ? meta.getAttribute('content') : ''
    },
    closeModal() {
      this.$emit('closeModal')
    },
    updateTag() {
      if (this.name === '' || this.name === this.initialName) {
        return null
      }
      const params = {
        tag: { name: this.name }
      }
      fetch(`/api/tags/${this.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRF-Token': this.token()
        },
        credentials: 'same-origin',
        redirect: 'manual',
        body: JSON.stringify(params)
      })
        .then(() => {
          this.$emit('updateTag', this.name)
          this.closeModal()
        })
        .catch((error) => {
          console.warn(error)
        })
    }
  }
}
</script>
