// app/javascript/components/UserRoleStatusSpan.jsx
import React from 'react'

export default function UserRoleStatusSpan({
  user,
  spanClassName,
  className,
  src,
  title,
  alt
}) {
  const roleClass = `is-${user.primary_role}`
  const joiningStatusClass =
    user.joining_status === 'new-user' ? 'is-new-user' : ''
  return (
    <span
      className={`a-user-role ${spanClassName} ${roleClass} ${joiningStatusClass}`}>
      <img className={className} src={src} title={title} alt={alt} />
    </span>
  )
}

export function getUserRoleStatusClass(user) {
  return `is-${user.primary_role} is-${user.joining_status}`
}

// app/javascript/user_role_status_span.vue
<template lang="pug">
span(:class='["a-user-role", roleClass, joiningStatusClass]')
  img.card-list-item__user-icon.a-user-icon(
    :title='user.icon_title',
    :alt='user.icon_title',
    :src='user.avatar_url')
</template>
<script>
export default {
  name: 'UserRoleStatusSpan',
  props: {
    user: { type: Object, required: true }
  },
  computed: {
    roleClass() {
      return `is-${this.user.primary_role}`
    },
    joiningStatusClass() {
      return `is-${this.user.joining_status}`
    }
  }
}
</script>
