// app/javascript/components/UserPracticeProgress.jsx
import React from 'react'

export default function UserPracticeProgress({ user }) {
  const percentage = user.cached_completed_percentage
  const fraction = user.completed_fraction

  const roundedPercentage = user.graduated_on
    ? '100%'
    : Math.round(percentage) + '%'

  const ariaValuenow = user.graduated_on ? 100 : percentage

  const completedPracticesProgressNumber = user.graduated_on ? '卒業' : fraction

  return (
    <div className="completed-practices-progress">
      <div className="completed-practices-progress__bar-container">
        <div className="completed-practices-progress__bar"></div>
        <div
          className="completed-practices-progress__percentage-bar"
          aria-valuemax="100"
          aria-valuemin="0"
          aria-valuenow={ariaValuenow}
          role="progressbar"
          style={{ width: roundedPercentage }}></div>
      </div>
      <div className="completed-practices-progress__number">
        {completedPracticesProgressNumber}
      </div>
    </div>
  )
}

// app/javascript/user-practice-progress.vue
<template lang="pug">
.completed-practices-progress
  .completed-practices-progress__bar-container
    .completed-practices-progress__bar
    .completed-practices-progress__percentage-bar(
      aria-valuemax='100',
      aria-valuemin='0',
      :aria-valuenow='ariaValuenow()',
      role='progressbar',
      :style='`width: ${roundedPercentage}`'
    )
  .completed-practices-progress__number
    | {{ completedPracticesProgressNumber() }}
</template>
<script>
export default {
  props: {
    user: { type: Object, required: true }
  },
  data() {
    return {
      percentage: this.user.cached_completed_percentage,
      fraction: this.user.completed_fraction
    }
  },
  computed: {
    roundedPercentage() {
      return this.user.graduated_on
        ? '100%'
        : Math.round(this.percentage) + '%'
    }
  },
  methods: {
    ariaValuenow() {
      return this.user.graduated_on ? 100 : this.percentage
    },
    completedPracticesProgressNumber() {
      return this.user.graduated_on ? '卒業' : this.fraction
    }
  }
}
</script>
