// app/javascript/components/User.jsx
import React from 'react'
import Following from './Following.jsx'
import UserActivityCounts from './UserActivityCounts.jsx'
import UserSns from './UserSns.jsx'
import UserTags from './UserTags.jsx'
import UserPracticeProgress from './UserPracticeProgress.jsx'

export default function User({ user, currentUser }) {
  const userDescParagraphs = () => {
    let description = user.description
    description =
      description.length <= 200
        ? description
        : description.substring(0, 200) + '...'
    const paragraphs = description.split(/\n|\r\n/).map((text, i) => {
      return {
        id: i,
        text: text
      }
    })
    return paragraphs
  }

  const roleClass = () => `is-${user.primary_role}`

  return (
    <div className="col-xxl-3 col-xl-4 col-lg-4 col-md-6 col-xs-12">
      <div className="users-item">
        <div className={`users-item__inner a-card ${roleClass()}`}>
          {currentUser &&
            (currentUser.mentor || currentUser.admin) &&
            user.student_or_trainee && (
              <div className="users-item__inactive-message-container is-only-mentor">
                {user.roles.includes('retired') && (
                  <div className="users-item__inactive-message">
                    退会しました
                  </div>
                )}
                {user.roles.includes('hibernationed') && (
                  <div className="users-item__inactive-message">
                    休会中: {user.hibernated_at}〜(
                    {user.hibernation_elapsed_days}日経過)
                  </div>
                )}
                {!user.active && (
                  <div className="users-item__inactive-message">
                    1ヶ月以上ログインがありません
                  </div>
                )}
              </div>
            )}
          <header className="users-item__header">
            <div className="users-item__header-inner">
              <div className="users-item__header-start">
                <div className="users-item__icon">
                  <a href={user.url}>
                    <span className={`a-user-role ${roleClass()}`}>
                      <img
                        className="users-item__user-icon-image a-user-icon"
                        title={user.icon_title}
                        alt={user.icon_title}
                        src={user.avatar_url}
                      />
                    </span>
                  </a>
                </div>
              </div>
              <div className="users-item__header-end">
                <div className="card-list-item__rows">
                  <div className="card-list-item__row">
                    <div className="card-list-item-title">
                      <div className="card-list-item-title__end">
                        {user.company && user.company.logo_url && (
                          <a href={user.company.url}>
                            <img
                              className="user-item__company-logo"
                              src={user.company.logo_url}
                            />
                          </a>
                        )}
                        <a
                          className="card-list-item-title__title is-lg a-text-link"
                          href={user.url}>
                          {user.login_name}
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="card-list-item__row">
                    <div className="card-list-item-meta">
                      <div className="card-list-item-meta__items">
                        <div className="card-list-item-meta__item">
                          <div className="a-meta">{user.name}</div>
                        </div>
                        <div className="card-list-item-meta__item">
                          {user.discord_profile.times_url ? (
                            <a
                              className="a-meta"
                              href={user.discord_profile.times_url}>
                              <i className="fa-brands fa-discord"></i>
                              {user.discord_profile.account_name}
                            </a>
                          ) : (
                            <div className="a-meta">
                              <i className="fa-brands fa-discord"></i>
                              {user.discord_profile.account_name}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <UserSns user={user} />
              </div>
            </div>
            <UserActivityCounts user={user} />
          </header>
          <div className="users-item__body">
            <div className="users-item__description a-short-text">
              {userDescParagraphs().map((paragraph) => (
                <p key={paragraph.id}>{paragraph.text}</p>
              ))}
            </div>
            <div className="users-item__tags">
              <UserTags user={user} />
            </div>
          </div>
          <UserPracticeProgress user={user} />
          <hr className="a-border-tint" />
          <footer className="card-footer users-item__footer">
            <div className="card-main-actions">
              <ul className="card-main-actions__items">
                {currentUser.id !== user.id &&
                  currentUser.adviser &&
                  user.company &&
                  currentUser.company_id === user.company.id && (
                    <li className="card-main-actions__item">
                      <div className="a-button is-disabled is-sm is-block">
                        <i className="fa-solid fa-check"></i>
                        <span>自社研修生</span>
                      </div>
                    </li>
                  )}
                {currentUser.id !== user.id && (
                  <li className="card-main-actions__item">
                    <Following
                      isFollowing={user.isFollowing}
                      userId={user.id}
                      isWatching={user.isWatching}
                    />
                  </li>
                )}
                {currentUser.admin && user.talkUrl && (
                  <li className="card-main-actions__item is-only-mentor">
                    <a
                      className="a-button is-secondary is-sm is-block"
                      href={user.talkUrl}>
                      相談部屋
                    </a>
                  </li>
                )}
              </ul>
            </div>
          </footer>
        </div>
      </div>
    </div>
  )
}

// app/javascript/user.vue
<template lang="pug">
.col-xxl-3.col-xl-4.col-lg-4.col-md-6.col-xs-12
  .users-item
    .users-item__inner.a-card
      .users-item__inactive-message.is-only-mentor(
        v-if='currentUser.mentor && user.student_or_trainee && !user.active'
      )
        | 1ヶ月以上ログインがありません
      header.users-item__header
        .users-item__header-inner
          .users-item__header-start
            .users-item__icon
              a(:href='user.url')
                img.users-item__user-icon-image.a-user-icon(
                  :title='user.icon_title',
                  :alt='user.icon_title',
                  :src='user.avatar_url',
                  :class='[roleClass, daimyoClass]'
                )
          .users-item__header-end
            .users-item__name
              a.users-item__name-link(:href='user.url')
                | {{ loginName }}
              a(
                v-if='user.company && user.company.logo_url',
                :href='user.company.url'
              )
                img.user-item__company-logo(:src='user.company.logo_url')
            ul.users-item-names
              li.users-item-names__item
                .users-item-names__ful-name
                  | {{ user.name }}
              li.users-item-names__item(v-if='user.discord_account')
                .users-item-names__chat
                  .users-item-names__chat-label
                    i.fab.fa-discord
                  a.users-item-names__chat-value(:href='user.times_url')(
                    v-if='user.times_url'
                  )
                    | {{ user.discord_account }}
                  span.users-item-names__chat-value(v-else)
                    | {{ user.discord_account }}
        user-sns(:user='user')
      .users-item__body
        .users-item__description.a-short-text
          p(v-for='paragraph in userDescParagraphs', :key='paragraph.id')
            | {{ paragraph.text }}
        .users-item__tags
          user-tags(:user='user')
      user-practice-progress(:user='user')
      footer.card-footer
        .card-main-actions
          ul.card-main-actions__items
            li.card-main-actions__item(
              v-if='currentUser.id != user.id && currentUser.adviser == true && user.company && currentUser.company_id == user.company.id'
            )
              .a-button.is-disabled.is-md.is-block
                i.fas.fa-check
                span
                  | 自社研修生
            li.card-main-actions__item(v-else-if='currentUser.id != user.id')
              following(
                :isFollowing='user.isFollowing',
                :userId='user.id',
                :isWatching='user.isWatching'
              )
            li.card-main-actions__item.is-only-admin(
              v-if='currentUser.admin && user.talkUrl'
            )
              a.a-button.is-secondary.is-md.is-block(:href='user.talkUrl')
                | 相談部屋
</template>
<script>
import Following from './following.vue'
import UserSns from './user-sns.vue'
import UserTags from './user-tags.vue'
import UserPracticeProgress from './user-practice-progress.vue'

export default {
  components: {
    following: Following,
    'user-sns': UserSns,
    'user-tags': UserTags,
    'user-practice-progress': UserPracticeProgress
  },
  props: {
    user: { type: Object, required: true },
    currentUser: { type: Object, required: true }
  },
  computed: {
    loginName() {
      return this.user.daimyo
        ? '★' + this.user.login_name
        : this.user.login_name
    },
    userDescParagraphs() {
      let description = this.user.description
      description =
        description.length <= 200
          ? description
          : description.substring(0, 200) + '...'
      const paragraphs = description.split(/\n|\r\n/).map((text, i) => {
        return {
          id: i,
          text: text
        }
      })
      return paragraphs
    },
    roleClass() {
      return `is-${this.user.primary_role}`
    },
    daimyoClass() {
      return { 'is-daimyo': this.user.daimyo }
    }
  }
}
</script>
