// app/javascript/components/UserTags.jsx
import React from 'react'

export default function UserTags({ user }) {
  const tags = user.tag_list

  if (tags.length === 0) {
    return null
  }

  return (
    <div className="tag-links">
      <ul className="tag-links__items">
        {tags.map((tag) => (
          <li className="tag-links__item" key={tag}>
            <a
              className="tag-links__item-link"
              href={`/users/tags/${encodeURIComponent(tag)}`}>
              {tag}
            </a>
          </li>
        ))}
      </ul>
    </div>
  )
}

// app/javascript/user-tags.vue
<template lang="pug">
.tag-links
  ul.tag-links__items(v-if='tags.length !== 0')
    li.tag-links__item(v-for='tag in tags', :key='tag')
      a.tag-links__item-link(:href='`/users/tags/${tag}`')
        | {{ tag }}
</template>
<script>
export default {
  props: {
    user: { type: Object, required: true }
  },
  data() {
    return {
      tags: this.user.tag_list
    }
  }
}
</script>
