// app/javascript/components/UserSns.jsx
import React from 'react'

export default function UserSns({ user }) {
  const githubUrl = `https://github.com/${user.github_account}`
  const twitterUrl = `https://twitter.com/${user.twitter_account}`

  return (
    <div className="sns-links">
      <ul className="sns-links__items is-button-group">
        <li className="sns-links__item">
          {user.github_account ? (
            <a
              className="sns-links__item-link a-button is-sm is-secondary is-icon"
              href={githubUrl}>
              <i className="fa-brands fa-github-alt"></i>
            </a>
          ) : (
            <div className="sns-links__item-link a-button is-sm is-disabled is-icon">
              <i className="fa-brands fa-github-alt"></i>
            </div>
          )}
        </li>
        <li className="sns-links__item">
          {user.twitter_account ? (
            <a
              className="sns-links__item-link a-button is-sm is-secondary is-icon"
              href={twitterUrl}>
              <i className="fa-brands fa-x-twitter"></i>
            </a>
          ) : (
            <div className="sns-links__item-link a-button is-sm is-disabled is-icon">
              <i className="fa-brands fa-x-twitter"></i>
            </div>
          )}
        </li>
        <li className="sns-links__item">
          {user.facebook_url ? (
            <a
              className="sns-links__item-link a-button is-sm is-secondary is-icon"
              href={user.facebook_url}>
              <i className="fa-brands fa-facebook-square"></i>
            </a>
          ) : (
            <div className="sns-links__item-link a-button is-sm is-disabled is-icon">
              <i className="fa-brands fa-facebook-square"></i>
            </div>
          )}
        </li>
        <li className="sns-links__item">
          {user.blog_url ? (
            <a
              className="sns-links__item-link a-button is-sm is-secondary is-icon"
              href={user.blog_url}>
              <i className="fa-solid fa-blog"></i>
            </a>
          ) : (
            <div className="sns-links__item-link a-button is-sm is-disabled is-icon">
              <i className="fa-solid fa-blog"></i>
            </div>
          )}
        </li>
        <li className="sns-links__item">
          {user.discord_profile.times_url ? (
            <a
              className="sns-links__item-link a-button is-sm is-secondary is-icon"
              href={user.discord_profile.times_url}>
              <i className="fa-solid fa-clock"></i>
            </a>
          ) : (
            <div className="sns-links__item-link a-button is-sm is-disabled is-icon">
              <i className="fa-solid fa-clock"></i>
            </div>
          )}
        </li>
      </ul>
    </div>
  )
}

// app/javascript/user-sns.vue
<template lang="pug">
.sns-links
  ul.sns-links__items.is-button-group
    li.sns-links__item
      a.sns-links__item-link.a-button.is-sm.is-secondary.is-icon(
        v-if='user.github_account',
        :href='githubUrl'
      )
        i.fa-brands.fa-github-alt
      .sns-links__item-link.a-button.is-sm.is-disabled.is-icon(v-else)
        i.fa-brands.fa-github-alt
    li.sns-links__item
      a.sns-links__item-link.a-button.is-sm.is-secondary.is-icon(
        v-if='user.twitter_account',
        :href='twitterUrl'
      )
        i.fa-brands.fa-twitter
      .sns-links__item-link.a-button.is-sm.is-disabled.is-icon(v-else)
        i.fa-brands.fa-twitter
    li.sns-links__item
      a.sns-links__item-link.a-button.is-sm.is-secondary.is-icon(
        v-if='user.facebook_url',
        :href='user.facebook_url'
      )
        i.fa-brands.fa-facebook-square
      .sns-links__item-link.a-button.is-sm.is-disabled.is-icon(v-else)
        i.fa-brands.fa-facebook-square
    li.sns-links__item
      a.sns-links__item-link.a-button.is-sm.is-secondary.is-icon(
        v-if='user.blog_url',
        :href='user.blog_url'
      )
        i.fa-solid.fa-blog
      .sns-links__item-link.a-button.is-sm.is-disabled.is-icon(v-else)
        i.fa-solid.fa-blog
    li.sns-links__item
      a.sns-links__item-link.a-button.is-sm.is-secondary.is-icon(
        v-if='user.times_url',
        :href='user.times_url'
      )
        i.fa-solid.fa-clock
      .sns-links__item-link.a-button.is-sm.is-disabled.is-icon(v-else)
        i.fa-solid.fa-clock
</template>
<script>
export default {
  props: {
    user: { type: Object, required: true }
  },
  computed: {
    githubUrl() {
      return `https://github.com/${this.user.github_account}`
    },
    twitterUrl() {
      return `https://twitter.com/${this.user.twitter_account}`
    }
  }
}
</script>
