// app/javascript/notifications_bell.vue
<template lang="pug">
li.header-links__item(v-bind:class='hasCountClass')
  label.header-links__link.test-show-notifications(
    for='header-notification-pc',
    @click='clickBell')
    .header-links__link.test-bell
      .header-notification-icon
        .header-notification-count.a-notification-count.test-notification-count(
          v-show='notificationExist') {{ this.notificationCount }}
        .header-notification-count.a-notification-count.is-loading(
          v-if='loading')
        i.fa-solid.fa-bell
        .header-links__link-label 通知
  input#header-notification-pc.a-toggle-checkbox(
    v-if='notificationExist',
    type='checkbox')
  .header-dropdown
    label.header-dropdown__background(for='header-notification-pc')
    .header-dropdown__inner.is-notification
      ul.header-dropdown__items
        li.header-dropdown__item(v-for='notification in notifications')
          a.header-dropdown__item-link.unconfirmed_link(
            :href='notification.path')
            .header-notifications-item__body
              span.a-user-role(:class="'is-' + notification.sender.primary_role")
                img.header-notifications-item__user-icon.a-user-icon(
                  :src='notification.sender.avatar_url')
                .header-notifications-item__message
                  p.test-notification-message {{ notification.message }}
                time.header-notifications-item__created-at {{ createdAtFromNow(notification.created_at) }}
      footer.header-dropdown__footer
        a.header-dropdown__footer-link(href='/notifications?status=unread') 全ての未読通知
        a.header-dropdown__footer-link(href='/notifications') 全ての通知
        a.header-dropdown__footer-link(
          href='/notifications/allmarks',
          ref='nofollow',
          data-method='post') 全て既読にする
        button.header-dropdown__footer-link(@click='openUnconfirmedItems()') 全て別タブで開く
</template>
<script>
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'
dayjs.extend(relativeTime)

export default {
  data() {
    return {
      notifications: [],
      loading: false
    }
  },
  computed: {
    notificationCount() {
      const count = this.notifications.length
      return count > 99 ? '99+' : String(count)
    },
    notificationExist() {
      return this.notifications.length > 0
    },
    hasCountClass() {
      return this.notificationExist ? 'has-count' : 'has-no-count'
    }
  },
  created() {
    this.loading = true
    fetch(`/api/notifications.json?status=unread`, {
      method: 'GET',
      headers: {
        'X-Requested-With': 'XMLHttpRequest'
      },
      credentials: 'same-origin',
      redirect: 'manual'
    })
      .then((response) => {
        return response.json()
      })
      .then((json) => {
        json.notifications.forEach((n) => {
          this.notifications.push(n)
          console.log(n)
        })
      })
      .catch((error) => {
        console.warn(error)
      })
      .finally(() => {
        this.loading = false
      })
  },
  methods: {
    clickBell() {
      if (!this.notificationExist) {
        location.href = '/notifications'
      }
    },
    createdAtFromNow(createdAt) {
      return dayjs(createdAt).fromNow()
    },
    openUnconfirmedItems() {
      const links = document.querySelectorAll(
        '.header-dropdown__item-link.unconfirmed_link'
      )
      links.forEach((link) => {
        window.open(link.href, '_target', 'noopener')
      })
    }
  }
}
</script>

// app/javascript/components/NotificationsBell/NotificationsBell.jsx
import React, { useState } from 'react'
import useSWR from 'swr'
import BellButton from './BellButton'
import fetcher from '../../fetcher'
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'
dayjs.extend(relativeTime)

export default function NotificationsBell() {
  const [showNotifications, setShowNotifications] = useState(false)

  const url = '/api/notifications.json?status=unread'
  const { data, error } = useSWR(url, fetcher)

  const notificationExist = data?.notifications.length > 0
  const hasCountClass = notificationExist ? 'has-count' : 'has-no-count'

  const clickOutsideNotifications = (e) => {
    if (e.target !== e.currentTarget) return

    setShowNotifications(false)
  }

  const openUnconfirmedItems = () => {
    const links = document.querySelectorAll(
      '.header-dropdown__item-link.unconfirmed_link'
    )
    links.forEach((link) => {
      window.open(link.href, '_target', 'noopener')
    })
  }

  if (error) {
    console.warn(error)
    return <div>failed to load</div>
  }

  return (
    <div className={hasCountClass}>
      <BellButton setShowNotifications={setShowNotifications} />
      {data && showNotifications && (
        <div>
          <label
            className="header-dropdown__background"
            onClick={clickOutsideNotifications}></label>
          <div className="header-dropdown__inner is-notification">
            <ul className="header-dropdown__items">
              {data.notifications.map((notification) => {
                return (
                  <Notification
                    key={notification.id}
                    notification={notification}
                  />
                )
              })}
            </ul>
            <footer className="header-dropdown__footer">
              <a
                href="/notifications?status=unread"
                className="header-dropdown__footer-link">
                全ての未読通知
              </a>
              <a href="/notifications" className="header-dropdown__footer-link">
                全ての通知
              </a>
              <a
                href="/notifications/allmarks"
                className="header-dropdown__footer-link"
                data-method="post">
                全て既読にする
              </a>
              <button
                className="header-dropdown__footer-link"
                onClick={openUnconfirmedItems}>
                全て別タブで開く
              </button>
            </footer>
          </div>
        </div>
      )}
    </div>
  )
}

function Notification({ notification }) {
  const createdAtFromNow = (createdAt) => {
    return dayjs(createdAt).fromNow()
  }

  return (
    <li className="header-dropdown__item">
      <a
        href={notification.path}
        className="header-dropdown__item-link unconfirmed_link">
        <div className="header-notifications-item__body">
          <span
            className={`a-user-role header-notifications-item__user-icon is-${notification.sender.primary_role}`}>
            <img
              src={notification.sender.avatar_url}
              className="a-user-icon"
              alt="User Icon"
            />
          </span>
          <div className="header-notifications-item__message">
            <p className="test-notification-message">{notification.message}</p>
          </div>
          <time className="header-notifications-item__created-at">
            {createdAtFromNow(notification.created_at)}
          </time>
        </div>
      </a>
    </li>
  )
}
